### ISSUE TITLE
ubuntu13: VCRHTTPSConnection instance has no attribute 'set_tunnel'

### ISSUE THREAD

**Issue by suederat** [kevin1024/vcrpy#111]
I dont know why this issue is showing up, not sure how i broke vcrpy or its dependents. I tested code that still works on my macbook. Here are some facts from the ubuntu env in which this is showing up.
# test_foo.py

import urllib2
import vcr

@vcr.use_cassette('stmp')
def test_hello_go_ogle():
    urllib2.urlopen('https://www.google.com')

stack-trace-------------
exc = (<type 'exceptions.AttributeError'>, AttributeError("VCRHTTPSConnection instance has no attribute 'set_tunnel'",), <traceback object at 0xa0f1cd4>)
catch = None

```
@wraps(f)
def inner(*args, **kw):
    self.__enter__()

    exc = _NO_EXCEPTION
    try:
        result = f(*args, **kw)
    except Exception:
        exc = sys.exc_info()

    catch = self.__exit__(*exc)

    if not catch and exc is not _NO_EXCEPTION:
```

> ```
>       _reraise(*exc)
> ```

/usr/local/lib/python2.7/dist-packages/contextdecorator.py:102: 

---

/usr/local/lib/python2.7/dist-packages/contextdecorator.py:95: in inner
    result = f(_args, *_kw)
test_foo.py:6: in test_hello_go_ogle
    urllib2.urlopen('https://www.google.com')
/usr/lib/python2.7/urllib2.py:126: in urlopen
    return _opener.open(url, data, timeout)
/usr/lib/python2.7/urllib2.py:400: in open
    response = self._open(req, data)
/usr/lib/python2.7/urllib2.py:418: in _open
    '_open', req)
/usr/lib/python2.7/urllib2.py:378: in _call_chain
    result = func(*args)
/usr/lib/python2.7/urllib2.py:1215: in https_open
    return self.do_open(httplib.HTTPSConnection, req)
# pip freeze

oauth==1.0.1
onboard==0.97.1
oneconf==0.2.8.1
oslo.config==1.3.0
pbr==0.8.2
pexpect==3.2
piston-mini-client==0.7.2
prettytable==0.7.2
protobuf==2.4.1
py==1.4.22
pyOpenSSL==0.12
pycrypto==2.6.1
pycups==1.9.61
pycurl==7.19.0
pyinotify==0.9.2
pyparsing==2.0.2
pyserial==2.5
pysmbc==1.0.13
pytest==2.6.1
pytest-cache==1.0
python-apt==0.8.3ubuntu7
python-dateutil==1.5
python-debian==0.1.21ubuntu1
python-keystoneclient==0.9.0
python-neutronclient==2.3.4
python-novaclient==2.17.0
python-virtkey==0.60.0
pytz==2014.4
pyxdg==0.19
reportlab==2.5
rhythmbox-ubuntuone==3.0.0
rope==0.10.2
sessioninstaller==0.0.0
simplegeneric==0.7
simplejson==3.5.2
software-center-aptd-plugins==0.0.0
spur==0.3.12
stevedore==0.15
system-service==0.1.6
ubuntuone-couch==0.3.0
ubuntuone-installer==3.0.2
ubuntuone-storage-protocol==3.0.2
ufw==0.31.1-1
unattended-upgrades==0.1
unity-lens-video==0.3.5
unity-scope-video-remote==0.3.5
usb-creator==0.2.23
virtualenv==1.7.1.2
virtualenv-clone==0.2.5
virtualenvwrapper==4.3.1
wadllib==1.3.0
wsgiref==0.1.2
xdiagnose==2.5.2
xkit==0.0.0
zope.interface==3.6.1

same result outside of virtualenv after doing an upgrade
Babel==1.3
Brlapi==0.5.6
GnuPGInterface==0.3.2
Mako==0.5.0
MarkupSafe==0.15
PAM==0.4.2
PIL==1.1.7
PyYAML==3.11
Twisted-Core==11.1.0
Twisted-Names==11.1.0
Twisted-Web==11.1.0
adium-theme-ubuntu==0.3.2
apt-xapian-index==0.44
apturl==0.5.1ubuntu3
argparse==1.2.1
chardet==2.0.1
cliff==1.6.1
cmd2==0.6.7
command-not-found==0.2.44
configglue==1.0
configobj==4.7.2
contextdecorator==0.10.0
contextlib2==0.4.0
debtagshw==0.1
decorator==3.3.2
defer==1.0.2
dirspec==3.0.0
duplicity==0.6.18
ecdsa==0.11
elpy==1.5.1
execnet==1.2.0
flake8==2.2.3
httplib2==0.9
ipaddr==2.1.11
ipython==0.12.1
iso8601==0.1.10
jedi==0.8.1-final0
jockey==0.9.7
keyring==0.7.1
language-selector==0.1
launchpadlib==1.9.12
lazr.restfulclient==0.12.0
lazr.uri==1.0.3
louis==2.3.0
lxml==3.3.5
mccabe==0.2.1
mock==1.0.1
netaddr==0.7.11
nvidia-common==0.0.0
oauth==1.0.1
onboard==0.97.1
oneconf==0.2.8.1
oslo.config==1.3.0
paramiko==1.15.1
pbr==0.8.2
pep8==1.5.7
pexpect==3.2
piston-mini-client==0.7.2
prettytable==0.7.2
protobuf==2.4.1
py==1.4.22
pyOpenSSL==0.12
pycrypto==2.6.1
pycups==1.9.61
pycurl==7.19.0
pyflakes==0.8.1
pyinotify==0.9.2
pyparsing==2.0.2
pyserial==2.5
pysmbc==1.0.13
pytest==2.6.1
pytest-cache==1.0
python-apt==0.8.3ubuntu7
python-dateutil==1.5
python-debian==0.1.21ubuntu1
python-keystoneclient==0.9.0
python-neutronclient==2.3.4
python-novaclient==2.17.0
python-virtkey==0.60.0
pytz==2014.4
pyxdg==0.19
reportlab==2.5
requests==2.3.0
rhythmbox-ubuntuone==3.0.0
rope==0.10.2
sessioninstaller==0.0.0
simplegeneric==0.7
simplejson==3.5.2
six==1.8.0
software-center-aptd-plugins==0.0.0
spur==0.3.12
stevedore==0.15
system-service==0.1.6
ubuntuone-couch==0.3.0
ubuntuone-installer==3.0.2
ubuntuone-storage-protocol==3.0.2
ufw==0.31.1-1
unattended-upgrades==0.1
unity-lens-video==0.3.5
unity-scope-video-remote==0.3.5
usb-creator==0.2.23
vcrpy==1.1.1
virtualenv==1.7.1.2
virtualenv-clone==0.2.5
virtualenvwrapper==4.3.1
wadllib==1.3.0
wrapt==1.9.0
wsgiref==0.1.2
xdiagnose==2.5.2
xkit==0.0.0
zope.interface==3.6.1

**Comment by mjholtkamp** [comment]
To revive this topic: I get the same error and I have a minimum working example:

```
$ cat mwe.py
import vcr
import urllib2

URL = 'https://google.com/'


def req():
    resp = urllib2.urlopen(URL)
    print("req2: {}".format(resp))

req()

with vcr.use_cassette('bla.yaml', record_mode='new_episodes'):
    req()
```

I ran the command with a proxy env set (bla.yaml doesn't exist):
```
$ https_proxy=https://localhost:3128/ python mwe.py
req2: <addinfourl at 4403567360 whose fp = <socket._fileobject object at 0x10670b8d0>>
Traceback (most recent call last):
  File "mwe.py", line 14, in <module>
    req()
  File "mwe.py", line 8, in req
    resp = urllib2.urlopen(URL)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1191, in do_open
    h.set_tunnel(req._tunnel_host, headers=tunnel_headers)
AttributeError: 'VCRHTTPSConnectionbla.yaml' object has no attribute 'set_tunnel'
```

without the proxy env set it works as expected (bla.yaml doesn't exist here either).
```
$ python mwe.py
req2: <addinfourl at 4352690584 whose fp = <socket._fileobject object at 0x1036728d0>>
req2: <addinfourl at 4352813320 whose fp = <socket._fileobject object at 0x1036728d0>>
```

I just pip installed vcrpy, nothing more:
```
$ pip freeze
contextlib2==0.5.3
funcsigs==1.0.2
mock==2.0.0
pbr==1.10.0
PyYAML==3.11
six==1.10.0
vcrpy==1.8.0
wrapt==1.10.8
```

It seems like `set_tunnel` is not only used for socks, but also for http(s) proxies.

If I change the URL to http (dropping the 's'), then both commands work well, so it's really the combination of https + proxy:

```
$ https_proxy=https://localhost:3128/ python mwe.py
req2: <addinfourl at 4575691120 whose fp = <socket._fileobject object at 0x110b3a8d0>>
req2: <addinfourl at 4575694648 whose fp = <socket._fileobject object at 0x110b28d50>>
$ python mwe.py
req2: <addinfourl at 4540772648 whose fp = <socket._fileobject object at 0x10e9d88d0>>
req2: <addinfourl at 4540775960 whose fp = <socket._fileobject object at 0x10e9c6d50>>
```

The proxy being used it cntlm by the way, don't know if that helps.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
