### ISSUE TITLE
Support for Tornado HTTP

### ISSUE THREAD

**Issue by breerly** [kevin1024/vcrpy#120]
Is Tornado's HTTP client not supported? Thanks

http://tornado.readthedocs.org/en/latest/httpclient.html

**Comment by breerly** [comment]
@IvanMalison any plans to add it?

**Comment by IvanMalison** [comment]
Not really, but there could be. Have you looked in to how hard this is? It might be as simple as adding some some patches to the PatchBuilder class in patch.py, but it might involve doing some work with stubbing/HTTPConnection or possibly even more custom logic.

**Comment by IvanMalison** [comment]
It looks like tornado's http uses its own IOStreamClasses for managing connections and stuff, so this could be a pretty involved change that might involve writing something like VCRConnection in the stubs file to patch these classes.

**Comment by breerly** [comment]
@abhinav @dilyandokov ^^

**Comment by IvanMalison** [comment]
@kevin1024 I'm going to be doing this week. It is going to basically require doing something similar to what is done with the VCRConnection stub all over again but entirely separately for both

pycurl (to handle the CurlHTTPClient) and in tornados own http stuff to handle the SimpleHTTPClient, unless we patch at a very high level, but then possibly miss out on automatically headers/some other things and also end up being somewhat inconsistent with the way the rest of vcrpy works. Any thoughts on this?

**Comment by kevin1024** [comment]
Wow ok.  Yeah sometime I fantasize about patching the socket and using a HTTP parser but that is a pretty big undertaking.

If you do add support for tornado I would obviously prefer that it works the same way as urllib2/requests - ie all features supported for all stubs.

I think the pycurl stub will be the most challenging.  Any idea how code reuse will work between the stubs?

**Comment by IvanMalison** [comment]
Actually the pycurl stub looks to be the easier of the two from what I can tell. Obviously we will be able to reuse the cassette.py/config.py/patch.py code, but unfortunately, I'm not sure that much in stubs/ will be very useful for this (except insofar as it serves as a template for how to handle patching). :( This is the main downside to patching at the level that we do.
