### ISSUE TITLE
Support for Thrift.

### ISSUE THREAD

**Issue by breerly** [kevin1024/vcrpy#122]
Thinking it would be great for users of thrift to do integration testing with VCRpy as well.

Thoughts?

**Comment by phoet** [comment]
does not look like this is possible any time soon?

**Comment by IvanMalison** [comment]
@breerly @phoet Given that thrift uses httplib vcrpy should already work if you are using that transport. As for getting socket support, that would basically require a massive rewrite of vcrpy that patches a layer lower than we are currently patching.

Vcrpy focuses on HTTP testing. I don't think tcp level testing is likely to be added any time soon (or ever).

**Comment by breerly** [comment]
I've tested that this does work when using Thrift's HTTP transport.
