### ISSUE TITLE
Unable to patch urllib2 after install_opener has been used.

### ISSUE THREAD

**Issue by breerly** [kevin1024/vcrpy#129]
We're using a custom opener with urllib2 (adding some additional sec features), looks something like so:

```python
urllib2.install_opener(urllib2.build_opener(CustomHTTPSOpener))
```

The opener overwrites the `https_open` method so that a custom connection object can be used. Something like the following:

```python
class CustomHTTPSOpener(urllib2.HTTPSHandler):
    def __init__(self, **kwargs):
        urllib2.HTTPSHandler.__init__(self)
        self._connect_args = kwargs

    def https_open(self, req):
        def connection_wrapper(host, **kwargs):
            all_kwargs = dict(self._connect_args)
            all_kwargs.update(kwargs)
            return CustomHTTPSConnection(host, **all_kwargs)

        return self.do_open(connection_wrapper, req)
```

Then when I use vcrpy, I get the following:

```
TypeError: unbound method __init__() must be called with VCRHTTPConnection myapp/tests/cassette.yaml instance as first argument (got CustomHTTPSConnection instance instead)
```

Any ideas? Thanks

**Comment by IvanMalison** [comment]
@breerly Can you supply a traceback?

Do you need any of the custom connection logic to run in your tests? If not, you might be able to get away with simply patching `CustomHTTPSConnection` with VCRHTTPSConnection.
The thing is that vcrpy would need to provide a hook to provide custom patches, which it does not currently do. If this type of solution would work for you, I can write some code to support this functionality.

**Comment by tiffanycheng** [comment]
No, the custom connection logic doesn't actually need to run. Patching the `CustomHTTPSConnection` with VCRHTTPSConnection should work.

**Comment by IvanMalison** [comment]
@tiffanycheng @breerly https://github.com/kevin1024/vcrpy/pull/133 should enable the behavior that you want.

All that you really need to do is use a custom vcr for patching that looks like:
``` python
from vcr.stubs import VCRHTTPSConnection
my_vcr = config.VCR(custom_patches=((wherever_it_lives, 'CustomHTTPSConnection', VCRHTTPSConnection),))
```

**Comment by IvanMalison** [comment]
Build failed on a flake, passed in my travis https://travis-ci.org/IvanMalison/vcrpy/builds/46351398

Rerunning.

**Comment by tiffanycheng** [comment]
@IvanMalison It worked perfectly!

**Comment by IvanMalison** [comment]
cool. I'm going to close this issue for now. Let me know if there are any more problems.
