### ISSUE TITLE
Add credential scrubbing funtionality to vcrpy?

### ISSUE THREAD

**Issue by IvanMalison** [kevin1024/vcrpy#132]
@kevin1024 What do you think about adding some type of credential scrubbing functionality to vcrpy? This is something that I implemented (somewhat messily) in https://github.com/IvanMalison/okcupyd/blob/master/okcupyd_testing/util.py, and I'm finding that I need similar types of things in other places that I use vcr.py.

It might be hard to come up with something that really works 100% of the time, but I imagine that other people encounter situations where they don't want to commit credentials to publicly hosted reposotories from time to time.

**Comment by kevin1024** [comment]
It's already in there :)

https://github.com/kevin1024/vcrpy#filter-sensitive-data-from-the-request

**Comment by kevin1024** [comment]
Please reopen if you had something else in mind though.

**Comment by IvanMalison** [comment]
sorry, I should have been clearer. Sometimes the relevant information is not in the queryparams or the header of the file, so I what I had to write that does this in a custom way is filtering for the request body, which can be particularly difficult because the request body is often gzipped. This is probably still a more obscure use case, so it might not be something that is worth includin gher.

**Comment by kevin1024** [comment]
Ahh yes I see, so stuff that's not in a header or a querysting, but in the body of the request.  You can of course do it with the before_record callbacks as you have already done.  You raise a good point with the gzip stuff - so far VCR.py has managed to avoid doing any gzipping/unzipping.

My philosophy with VCR's API is to take care of the 90% case super easily (credentials in headers or querystring) while still allowing you to handle the more complicated cases yourself.  I don't know how common a case this is but the gzipping scares me :)

Are you thinking just a find/replace on the body?

**Comment by IvanMalison** [comment]
Yeah I guess so. I had forgotten that vcrpy does have some oob request scrubbing functionality when I raised this issue (which already covers the 90% case pretty well as you mentioned), so I think it is probably fine to just ignore this (sorry).

I guess the main situation where you might find sensitive information in the body of a request is when it is a post request and it is part of a form. Doing so is not really a good practice (headers/query param are a much more common approach).
