### ISSUE TITLE
reduce duplication for integration tests of similar libs

### ISSUE THREAD

**Issue by aisch** [kevin1024/vcrpy#139]
for libs that do ~ the same thing (e.g. httplib, urllib2, urllib3, requests) most of the test *behavior* and *fixtures* are the same (see `e.g. tests/integration/test_urrlib2.py:test_cross_scheme`) but just copied around. is there a nice way to reduce that copying?

some ideas for that are here: https://github.com/kevin1024/vcrpy/pull/138.

**Comment by IvanMalison** [comment]
This is probably too difficult to do and would probably make the tests brittle and hard to understand. : / I hate copy pasta, but sometimes its hard to get around it.
