### ISSUE TITLE
xmlrpclib support

### ISSUE THREAD

**Issue by techtonik** [kevin1024/vcrpy#140]
`vcrpy` and `xmlrpclib` don't work together. Without vcr, the following code outputs tracker schema.

```
import vcr
import xmlrpclib

with vcr.use_cassette('xmlrpcvideo.yaml'):
  roundup_server = xmlrpclib.ServerProxy('http://bugs.python.org/xmlrpc', allow_none=True)
  print(roundup_server.schema())
```

With vcr it fails:

```
> python schema.py
Traceback (most recent call last):
  File "schema.py", line 6, in <module>
    print(roundup_server.schema())
  File "C:\Python27\Lib\xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\Lib\xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "C:\Python27\Lib\xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\Lib\xmlrpclib.py", line 1294, in single_request
    response = h.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
```

**Comment by IvanMalison** [comment]
Can you check if this still happens in https://github.com/kevin1024/vcrpy/compare/getresponse_should_take_kwargs (fdd1883)

**Comment by techtonik** [comment]
@IvanMalison, `TypeError` is gone, but `vcrpy` still doesn't work correctly - it fails to intercept payload. So, the problem may be somewhere in a different place. Headers are ok (although sent in different order), but body is an empty string and should by XML payload. So, the script still fails:

```
Traceback (most recent call last):
  File "schema.py", line 6, in <module>
    print(roundup_server.schema())
  File "C:\Python27\Lib\xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\Lib\xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "C:\Python27\Lib\xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\Lib\xmlrpclib.py", line 1312, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for bugs.python.org/xmlrpc: 400 Bad Request>
```

**Comment by techtonik** [comment]
Still a problem with `1.4.0` that `vcr` call is made with empty body of request resulting in `400 Bad Request` response.

**Comment by Diaoul** [comment]
I had the same issue, fixed it with my PR
@techtonik: can you confirm?

**Comment by techtonik** [comment]
@Diaoul Y-y-yes! This is fixed now. Waiting for release. =)

**Comment by Diaoul** [comment]
Yep, me too.
@IvanMalison: do you plan on making a new release with this fix?

**Comment by IvanMalison** [comment]
There will be a new vcrpy release by EOD PST this thursday that will also include a resolution to #120 . If you guys would like a release I could do a minor one right now.

**Comment by Diaoul** [comment]
EOD is fine by me

**Comment by techtonik** [comment]
I already patched my local version, so I can wait.

**Comment by Diaoul** [comment]
Just reinstalled everything and noticed this change didn't get released yet, can you make a new release?

Thanks

**Comment by IvanMalison** [comment]
New release is coming Tonight or tomorrow.

**Comment by techtonik** [comment]
Looks like it is released.

**Comment by IvanMalison** [comment]
Yep it is. Enjoy!
