### ISSUE TITLE
Use pytest-httpbin

### ISSUE THREAD

**Issue by kevin1024** [kevin1024/vcrpy#142]
This would help builds run faster and probably pass more consistently.  It's also one of my main motivations for writing it.  I just need to get the motivation to actually *use* it :-P

[pytest-httpbin](https://github.com/kevin1024/pytest-httpbin)

**Comment by IvanMalison** [comment]
Yeah, I had noticed that you hade made that library and was curious as to why vcrpy's tests don't use it. At least we have an issue for this now.

**Comment by kevin1024** [comment]
Working on this a bit in a branch: https://github.com/kevin1024/vcrpy/tree/pytest-httpbin

**Comment by danstender** [comment]
Just wanted to drop the note that we would appreciate it much for the Debian package [1] if the tests could run offline. Pytest-httpbin packaging is in progress.

[1] https://packages.qa.debian.org/v/vcr.py.html

**Comment by kevin1024** [comment]
Cool!  Yeah, I've been super busy lately but if I ever get a free weekend I definitely want to finish this up.

**Comment by danstender** [comment]
Welcome pytest-httpbin to Debian: https://tracker.debian.org/pkg/pytest-httpbin

**Comment by yarikoptic** [comment]
or may be meanwhile there is a way to skip tests which require network connection @kevin1024 ?  thanks in advance for the clarification

**Comment by danstender** [comment]
Any progress on this? Please combine your products :-)

**Comment by kevin1024** [comment]
Would love to but been super busy lately!

**Comment by kevin1024** [comment]
Now using it.  Not sure that the test suite is 100% offline yet but good progress!
