### ISSUE TITLE
Document Cassette format

### ISSUE THREAD

**Issue by techtonik** [kevin1024/vcrpy#143]
Is it worth to document the format of cassettes so that they could be built up and edited manually?

**Comment by IvanMalison** [comment]
Probably worth it to document the cassette format, but thou should be able to do what you are talking about by using an existing cassette as a template.

**Comment by kevin1024** [comment]
Sure, it would be nice to document the cassette format.

I consider the cassette format part of the public API, so changing it requires a major version bump.

Documenting it might also make external tools that work on cassettes possible.

It's worth noting that there are a couple different serializers for cassettes - JSON and YAML.  I don't think the actual structure of the cassette changes though.

**Comment by nathancahill** [comment]
I'm curious why a format like JSON or YAML is needed for cassettes? Couldn't it just work with raw HTTP? (since it's essentially just: body, headers, status)

**Comment by IvanMalison** [comment]
a) Most http libaries don't expose the http request as plaintext
b) we support a lot of features that let you mutate the request that require representations that aren't meremly string representations
c) serialization is format agnostic so you could easily serialize to an actual HTTP request body if you wanted

**Comment by nathancahill** [comment]
Makes a lot of sense. Thanks for the reply!

**Comment by techtonik** [comment]
Perhaps this can help both with validation and with migration/export/import of data structure https://pypi.python.org/pypi/trafaret

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
