### ISSUE TITLE
Dynamically generate cassette's name

### ISSUE THREAD

**Issue by klvbdmh** [kevin1024/vcrpy#151]
At the moment you have to explicitly name the cassette file in the path parameter when using a decorator:

    @vcr.use_cassette('article_header.yaml')
    def test_get_article_header_text_from_url():
        # rest of function...
    # cassette is saved as 'article_header.yaml'

Is it possible to dynamically generate cassette's name so it's taken from the decorated function instead?

    @vcr.use_cassette(func_name)
    def test_get_article_header_text_from_url():
        # rest of function...
    # cassette is saved as 'test_get_article_header_text_from_url.yaml'

**Comment by kevin1024** [comment]
Nothing built in, but I think Venmo did something like that with their custom decorator.  Read about it here:

http://engineering.venmo.com/blog/2014/04/30/vcrpy-at-venmo/

**Comment by IvanMalison** [comment]
Yep. I did this in:
https://github.com/IvanMalison/okcupyd/blob/master/okcupyd_testing/util.py#L227
It might be a bit hard to understand that without reading these docs:
http://okcupyd.readthedocs.org/en/latest/core.html#curry

The main trick is basically that a call to use_cassette actually returns a context manager/decorator, but the function name is not available at this time. You would need to do something like store the other parameters in a closure, wait for the second call, and then pass all the parameters in at once (sorry, I couldn't really describe this very well in words).

A really, really simple version of this would look like

```python
def auto_name_use_cassette(function):
    return vcr.use_cassette(function.__name__)(function)

@auto_name_use_cassette
def test_some_thing():
   test_stuff()
```
But this has the problem that you cant pass other parameters when you want to use this function.

If you want something that you can call like

```
@use_cassette
def test_function():
   test_stuff()
```

and

```
@use_cassette(param='value')
def test_function():
   test_stuff()
```

You are basically forced to write something like

http://okcupyd.readthedocs.org/en/latest/core.html#curry

**Comment by IvanMalison** [comment]
@kevin1024 What do you think about adding this as built in functionality to vcrpy?

**Comment by kevin1024** [comment]
Seems to be a pretty common use case; I'm happy to add it if we can come up with a good API.

**Comment by IvanMalison** [comment]
I'm imagining an identical API, except that if no path is provided, the function name + 'yaml' (or perhaps look at the serialization method) is used. As far as how it is used it would be exactly like https://github.com/IvanMalison/okcupyd/blob/master/okcupyd_testing/util.py#L227, but hopefully the implementation can be a bit less hacky.

**Comment by kevin1024** [comment]
Yeah, I think that's good.  So it would be

```python
@vcr.use_cassette
def test something():
    pass
```

I think it might be useful to have a method for overriding the filename generation.  Kind of like how you can have custom matchers.  The default filename generation would probably just use function name + $SERIALIZER_EXTENSION. Unless we should we include the module name too?

**Comment by IvanMalison** [comment]
sure, maybe just something like you can pass in a custom function that takes the function to be decorated as an argument and generates the filename.

I'm not sure If I see a way to do this without including the currying code that I mentioned earlier, now that I think about it.

I'm assuming that we want to maintain the interface that allows parameter passing....

**Comment by klvbdmh** [comment]
A "really, really simple version" posted by @IvanMalison works great. Thanks! I've added a simple string concatenation so that generated cassettes have .yaml extension.

I prefer this solution to more complicated approaches such as venmo's or okcupyd's. Obviously, out-of-box support would be the best.

Personally, the lack of parameter passing doesn't bother me so much. I set options through instantiating a VCR class. However, I can see how someone might want to pass different parameters to a certain test function and keep automated naming at the same time.

**Comment by kevin1024** [comment]
> I'm assuming that we want to maintain the interface that allows parameter passing

Definitely.  I think everything should be exactly the same except you can optionally omit the cassette name, and then it will be autogenerated.

**Comment by IvanMalison** [comment]
@klvbdmh You should be able to do what you want now with this tiny bit of additional configuration:
``` python
my_vcr = VCR(path_tranformer=VCR.ensure_suffix('.yaml')
```

**Comment by IvanMalison** [comment]
@kevin1024 I should have held off on putting this in master until you got a chance to take a look at it. I'm pretty happy with how things turned out, but the code is definitely more complicated, and though this is completely backwards compatible, there are some pretty significant changes underneath the hood.

Let me know what you think.
