### ISSUE TITLE
Autodoc Sphinx Docs/Improve Docstrings

### ISSUE THREAD

**Issue by IvanMalison** [kevin1024/vcrpy#157]
We should start using sphinx.

**Comment by Diaoul** [comment]
+1 for this, I was looking for the documentation link in the readme. Took me some time to figure out there is none :)

**Comment by kevin1024** [comment]
Yeah proper docs instead of a huge readme might be a good improvement.  It just kind of grew that way.

**Comment by kevin1024** [comment]
We have docs now! https://vcrpy.readthedocs.org/en/latest/
