### ISSUE TITLE
Error with body matcher for json, xmlrpc and form urlencoded

### ISSUE THREAD

**Issue by Diaoul** [kevin1024/vcrpy#166]
This is a tricky issue I encountered when using the body matcher on xmlrpc requests.

Symptoms: Sometimes the request won't match, sometimes it will, and this only affects certain requests. This occurs on Python 3.4 and I believe other python 3 versions but not on 2.7

Cause: An XMLRPC request has a body with XML inside which is generated from the parameters passed to the function call. Some parameters can be of dict type. xmlrpclib (or xmlrpc.client) will loop over items of the dict and generate the appropriate XML which will be the body of our POST request. Now items order is not guaranteed in dict and the behavior changed in python 3 such that the order of the same dict *can change anytime* and is not *more or less constant on the same computer* as in python 2. So the generated XML won't be necessarily the same as the one you recorded.

Fix suggestion: A custom xmlrpc body matcher that takes that into account and will compare the `struct` XML elements in the correct order.

The gzip compression didn't help me debuging this as I couldn't even read directly the cassettes...

**Comment by IvanMalison** [comment]
I mean you just need to write a custom matcher that does the right thing. This is expected behavior, not an issue with vcrpy.

Gzip compression is a feature that depends on the http request being made, and thus something we basically need to support. If you don't want your cassettes to be gzipped change you're request headers to prevent gzipping in your code.

You may want to look in
https://github.com/IvanMalison/okcupyd/blob/master/okcupyd_testing/util.py#L110
to see how to inspect the gzipped body of a request/response.

**Comment by Diaoul** [comment]
Yes, that's what I said, a proper matcher. I think as vcrpy supports xmlrpc it should come with an appropriate matcher. I'm working on it and will submit a PR.

Once done, this *must* be documented because the nature of this issue makes this hard to troubleshoot.

**Comment by Diaoul** [comment]
The issue is the same with json and form urlencoded. I'm going to edit the PR accordingly and fix the body matcher instead of adding a new one. This will be based on the Content-Type.

**Comment by Diaoul** [comment]
I plan to rename the current matcher `body` to `raw_body` and add a new `body` matcher that'll inspect the *Content-Type* header and do the following:
* `application/x-www-form-urlencoded` -> `parse_qs`
* `application/json` -> `json.loads`
* `text/xml` and `xmlrpc` in *User-Agent* -> `xmlrpc_client.loads`
* otherwise, same as `raw_body`

This gives the flexibility to use the same cassette for various body types (compared to if you had `form_body`, `xmlrpc_body` and `json_body` matchers) and save the user some trouble wondering why sometimes it works and sometimes it doesn't due to Python ordering of dicts and sets, especially in Python 3.
On the downside, this might be too clever for its own good so maybe rename it `content_typed_body` or something like that and keep current `body` matcher unchanged.It can be considered a breaking change as much as a bug fix, it really depends on use cases.

@IvanMalison: Thoughts?

**Comment by IvanMalison** [comment]
yeah that is fine. If all of the tests pass, you might as well just make it the default body matcher.

**Comment by kevin1024** [comment]
Hmm, what happens when the server gzips the responses?  If we are going to inspect the content we will need to start gunzipping the body.

I usually agree that whenever something surprising happens in your library, it's a bug.  It would be nice for this to work, as long as it doesn't turn into a rabbit hole :)

**Comment by kevin1024** [comment]
BTW our querystring marcher handles the same problem, it will Urldecode and sort before comparing, so it seems like a good idea to make the body matched behave in the same way as Lon as we can make it robust enough.  For example, if a response has the wrong content-type and we try to deserialize it, how should we handle it?  I would like vcr to be as transparent as possible - ie don't blow up with a vcr stack trace when trying to deserialize something.

**Comment by IvanMalison** [comment]
@kevin1024, gunzipping and then re gzipping it is not THAT hard. We can wrap it in a try except and fall back to raw_body matching as needed. Actually, I think we should eagerly try to raw_body match and only do the other stuff when that match is false, that way the matcher will be strictly more inclusive than the raw_body matcher.

**Comment by kevin1024** [comment]
> eagerly match

That is a really cool idea!

I think I'm on board, just being a curmudgeon.

**Comment by Diaoul** [comment]
Not a vcrpy expert but I could clearly see the request body (not gzip) even if the cassette showed gzip binary data so I believe gziping is done latter in the process. We only deal with uncompressed data here, at least in my use cases.

Comparing sorted `parse_qsl` results or directly `parse_qs` result is the same. I think the sorting part is not necessary and I went for the most straight forward approach. I can switch to sorted `parse_qsl` if you want consistency.

**Comment by Diaoul** [comment]
`body` is not by default on the `matched_on` so if an error is thrown hopefully user will (re-)read the documentation and see that this one is content-typed based. Then he can switch to raw_body if desired.
I don't think errors should pass silently and that we should fallback in raw body comparison. This can result in inconsistent behavior where some requests get compared by content type and some others don't even though sharing the same content type.

**Comment by IvanMalison** [comment]
> This can result in inconsistent behavior where some requests get compared by content type and some others don't even though sharing the same content type.

a) It's hard to imagine a scenario where raw_body would match but the content-type based approach would not, so I see no harm in doing that eagerly up front.
b) I don't think anyone suggested that errors should pass silently -- I was merely suggesting that if we had to deal with the fact that requests are gzipped we could try unzip and continue without unzipping in that case

> Not a vcrpy expert but I could clearly see the request body (not gzip) even if the cassette showed gzip binary data so I believe gziping is done latter in the process.

Are you sure about this? Even for the recorded request? That would surprise me quite a bit. I just looked at the code path, and i don't think that there would be anything that gunzips the recorded request. Can you send me the cassette with a gzipped request that you see this happening for. @kevin1024 may know better than I if something like this might be possible.

**Comment by kevin1024** [comment]
Vcr is definitely not doing any zipping or unzipping.  Pretty sure that is handled by the http library making the call (eg requests or urllib2) .  The zipped http response content is stored in the cassette and passed, still zipped, through to the http library doing the request.

**Comment by IvanMalison** [comment]
> Vcr is definitely not doing any zipping or unzipping.  Pretty sure that is handled by the http library making the call (eg requests or urllib2) .  The zipped http response content is stored in the cassette and passed, still zipped, through to the http library doing the request.

Yeah this is what I thought. However, since we are on the request side of things in this case, I think it might be possible that @Diaoul is right that the body might not be gzipped if the gzipping happens after we pass the request off to whatever http library is doing it. I think we should definitely still try to figure out what is going on there though so we don't run in to problems later.

**Comment by Diaoul** [comment]
Awesome, thanks!

**Comment by IvanMalison** [comment]
@Diaoul I moved some stuff around, so let me know if it doesn't suit your needs. Passes all of the original tests though so I think it should work.

**Comment by Diaoul** [comment]
Nice changes
