### ISSUE TITLE
Upgrading to 1.6.0 seems conditional extra_require are not working on setup

### ISSUE THREAD

**Issue by ialex** [kevin1024/vcrpy#169]
I receive this error when i upgraded to 1.6.0:
```
Traceback (most recent call last):
  File "run_tests.py", line 14, in <module>
    from tests.app_login_tests import MainSiteTest  # noqa
  File "/my_app/tests/app_login_tests.py", line 7, in <module>
    from vcr_setup import vcrlib
  File "/my_app/tests/vcr_setup.py", line 1, in <module>
    import vcr
  File "/usr/local/lib/python2.7/dist-packages/vcr/__init__.py", line 2, in <module>
    from .config import VCR
  File "/usr/local/lib/python2.7/dist-packages/vcr/config.py", line 8, in <module>
    from .compat import collections
  File "/usr/local/lib/python2.7/dist-packages/vcr/compat.py", line 4, in <module>
    import mock
ImportError: No module named mock
```

Looking at the commits i think this new conditionals imports are not working https://github.com/kevin1024/vcrpy/commit/41949f7dc64a2ddb8a9c2cb845eac7bb8b94380b#diff-2eeaed663bd0d25b7e608891384b7298R36 i'm installing the package using pip im on python 2.7.

**Comment by kevin1024** [comment]
Hmm, what version of pip are you running?  `pip -V`

I wonder if the conditional imports are a new feature.

**Comment by ialex** [comment]
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by IvanMalison** [comment]
hmm wouldn't it be the version of setup_tools that he has that matters? I guess it could be a pip thing, but setup_tools seems more likely.

**Comment by IvanMalison** [comment]
@ialex you can run `python -c 'from setuptools.version import __version__ as version; print(version)'` to check on this

**Comment by IvanMalison** [comment]
@kevin1024 this raises the question: Do we want to depend on new features in setuptools?

**Comment by kevin1024** [comment]
Ah yeah probably a setuptools version.

We probably want this to work on old versions of setuptools.  A lot of people don't have much control over their environment (yum install setuptools on RHEL5 installs some ancient version) and I don't want there to be any pain getting vcrpy installed.

**Comment by IvanMalison** [comment]
hmmm so you want to revert @graingert 's change in 41949f7dc64a2ddb8a9c2cb845eac7bb8b94380b?
I can see your reasoning. Maybe he can chime in on this?

**Comment by graingert** [comment]
This probably needs an "if setuptools.version < version_to_support_conditional:" that hacks it straight into the requirements

**Comment by IvanMalison** [comment]
@graingert I was hoping it wouldn't come to that, but I guess thats the situation we're in. Care to make the PR?

**Comment by graingert** [comment]
Looks like the functionality has been there forever https://bitbucket.org/pypa/setuptools/commits/1492#chg-setuptools/tests/test_dist_info.py

**Comment by graingert** [comment]
ah it's the old version of pip that's the problem

**Comment by ialex** [comment]
FYI
```
python -c 'from setuptools.version import __version__ as version; print(version)'
1.1.6
```

**Comment by graingert** [comment]
try creating a virtualenv, installing the latest pip, and then installing vcrpy.

**Comment by ialex** [comment]
On a new virtualenv and upgrading pip to => Successfully installed pip-7.1.0 it does install mock and contextlib2 properly, the questions is if the library should support old pip versions?.

```
pip install vcrpy
Collecting vcrpy
/Users/alex/.virtualenvs/vcrpy/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading vcrpy-1.6.0.tar.gz (155kB)
    100% |████████████████████████████████| 155kB 52kB/s
Collecting PyYAML (from vcrpy)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 8.9kB/s
Collecting wrapt (from vcrpy)
  Downloading wrapt-1.10.5.tar.gz
Collecting six>=1.5 (from vcrpy)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting contextlib2 (from vcrpy)
  Downloading contextlib2-0.4.0.tar.gz
Collecting mock (from vcrpy)
  Downloading mock-1.0.1.tar.gz (818kB)
    100% |████████████████████████████████| 819kB 20kB/s
Installing collected packages: PyYAML, wrapt, six, contextlib2, mock, vcrpy
  Running setup.py install for PyYAML
  Running setup.py install for wrapt
  Running setup.py install for contextlib2
  Running setup.py install for mock
  Running setup.py install for vcrpy
Successfully installed PyYAML-3.11 contextlib2-0.4.0 mock-1.0.1 six-1.9.0 vcrpy-1.6.0 wrapt-1.10.5
```

**Comment by IvanMalison** [comment]
@graingert has a pr (#170) out to fix this

**Comment by ialex** [comment]
Cool thanks every one for their support im going to close this issue.

**Comment by ldath** [comment]
Please create new version and upload it to pypi.

**Comment by graingert** [comment]
@ldath just run "pip install -U pip setuptools wheel" before installing any packages

**Comment by ldath** [comment]
This is not a problem for me ;) - I solved this moment after 1.6.0 shows - but human attention was needed to solve unexpected failing tests in jenkins. Maybe now I explained a little why after this kind of bug new version is needed in pypi.

**Comment by IvanMalison** [comment]
sorry this caused an issue for you @ldath . You might want to think about pinning to a particular vcrpy version in your requirements so that we can't break your tests by putting out a new version. I'll do a version bump/release this weekend.

**Comment by ldath** [comment]
I'm always pinning to particular version in the staging and production environments. Only in the development environment not. Anyway case closed.
