### ISSUE TITLE
use_cassette is not active for the duration of the generator/coroutine it decorates

### ISSUE THREAD

**Issue by charlax** [kevin1024/vcrpy#177]
When using Tornado's async client, `use_cassette` will not work when used as a decorator. It will only work if used as a context manager.

I'll write some code to reproduce the bug a bit later, but wanted to flag it now.

cc @abhinav

**Comment by IvanMalison** [comment]
It's not so much an issue with tornado's async client as it is an issues with the way generators/coroutines are handled. I've retitled this to indicate that.

**Comment by IvanMalison** [comment]
@abhinav @charlax @kevin1024 @graingert

I've put a fix for this in master in 21c176e, but it would be great if any of you could take a look at what I've done. I tried to support coroutines (in addition to generators) but this stuff is tricky business, and it is entirely possible that I didn't properly think about some edge case.

The most critical part of this change is here: https://github.com/kevin1024/vcrpy/commit/21c176ee1e7d3379f40e9330ab459a4a906f8cde#diff-dc8efcefc2dd30550706019d468fa580R89

but take a look at the other sections if you can as well.

**Comment by IvanMalison** [comment]
@kevin1024 Sorry about the failing build... I should have run the tests locally before pushing. Fix on the way.

**Comment by charlax** [comment]
I've verified that this is working on my test. Thanks a lot!

When the remote server is not running though, I get the following exception instead of an HTTP error:

```
Traceback (most recent call last):
  File "pytest_tornado/plugin.py", line 77, in pytest_pyfunc_call
    timeout=_timeout(pyfuncitem))
  File "tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "vcrpy/vcr/cassette.py", line 99, in _handle_coroutine
    to_send = yield to_yield
  File "vcrpy/vcr/cassette.py", line 71, in __exit__
    next(self.__finish, None)
  File "vcrpy/vcr/cassette.py", line 48, in _patch_generator
    cassette._save()
  File "vcrpy/vcr/cassette.py", line 255, in _save
    serializer=self._serializer
  File "vcrpy/vcr/persist.py", line 13, in save_cassette
    data = serialize(cassette_dict, serializer)
  File "vcrpy/vcr/serialize.py", line 57, in serialize
    cassette_dict['responses'],
  File "vcrpy/vcr/serializers/compat.py", line 10, in convert_to_unicode
    resp = convert_body_to_unicode(resp)
  File "vcrpy/vcr/serializers/compat.py", line 46, in convert_body_to_unicode
    resp['body']['string'] = resp['body']['string'].decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by IvanMalison** [comment]
But the response actually has a body?

**Comment by IvanMalison** [comment]
can you post the generated cassette? and or a simple repro?

**Comment by IvanMalison** [comment]
@charlax so if I understand correctly, the issue is that if you run a test that does not have an existing cassette and you try to record, you get this error instead of an http error?

Can you make a separate github issue for this and cc @abhinav .

**Comment by charlax** [comment]
Yes that's correct. Pretty sure I wasn't getting this with the other way though (using a context manager).
