### ISSUE TITLE
Exception when using vcr with Tornado coroutines

### ISSUE THREAD

**Issue by Sjord** [kevin1024/vcrpy#183]
When using VCR with the AsyncHTTPClient in a Tornado coroutine, I get an exception when creating the AsyncHTTPClient instance. Here is a short script to reproduce this:

```python
from tornado.httpclient import AsyncHTTPClient
from tornado import gen, ioloop
import vcr


@gen.coroutine
def some_function():
    AsyncHTTPClient()


with vcr.use_cassette('fixtures/vcr_cassettes/synopsis.yaml'):
    ioloop.IOLoop.instance().run_sync(some_function)
```

It gives the following exception:
```
Traceback (most recent call last):
  File "reproduce.py", line 13, in <module>
    ioloop.IOLoop.instance().run_sync(some_function)
  File "/home/sjoerd/.virtualenvs/bug/local/lib/python2.7/site-packages/tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "/home/sjoerd/.virtualenvs/bug/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/sjoerd/.virtualenvs/bug/local/lib/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "reproduce.py", line 9, in some_function
    AsyncHTTPClient()
  File "/home/sjoerd/.virtualenvs/bug/local/lib/python2.7/site-packages/tornado/httpclient.py", line 167, in __new__
    instance = super(AsyncHTTPClient, cls).__new__(cls, io_loop=io_loop,
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by mvschaik** [comment]
More minimal example:
```python
from tornado.httpclient import AsyncHTTPClient
import vcr 


def some_function():
    AsyncHTTPClient()

with vcr.use_cassette('fixtures/vcr_cassettes/synopsis.yaml'):
    some_function()
```

Same crash...

**Comment by mvschaik** [comment]
Just found out that the way of importing matters. This doesn't crash:

```python
import tornado.httpclient
import vcr 


with vcr.use_cassette('fixtures/vcr_cassettes/synopsis.yaml'):
    tornado.httpclient.AsyncHTTPClient()
```

**Comment by IvanMalison** [comment]
Yeah I mean that makes sense.  What is happening is that 'AsyncHTTPClient' is being patched in the
`tornado.httpclient` module, but you are importing that name directly which is putting it in your own module, and that is not being patched.

This is sort of an inherent problem with patching at this layer. @abhinav thoughts. we could move the patching?

**Comment by abhinav** [comment]
We could change it to patch the `fetch_impl` methods directly on the classes instead of replacing the classes at the module level. This would make make it also patch instances that already existed when entering the VCR context.

**Comment by kevin1024** [comment]
Yeah, I guess this isn't usually a problem since people don't normal use httplib directly, but people do directly use the tornado httpclient.

**Comment by abhinav** [comment]
Cool. I've got a fix incoming. Just a sec.

**Comment by mvschaik** [comment]
Thanks for the fast response!!
