### ISSUE TITLE
Environment variable configuration

### ISSUE THREAD

**Issue by Diaoul** [kevin1024/vcrpy#189]
It would be nice to be able to specify a global `record_once` from environment variable. Something like `VCRPY_RECORD_ONCE` is unique enough not to conflict with anything.

Would you consider this feature?

**Comment by kevin1024** [comment]
How about something like this:

```python
import vcr

my_vcr = vcr.VCR(
    record_mode=os.environ.get['VCR_RECORD_MODE']
)

with my_vcr.use_cassette('test.json'):
    # your http code here
```

**Comment by Diaoul** [comment]
I know I can do it in my code, I just believe this could be a nice feature and would integrate well with Travis for example without extra code.

**Comment by Diaoul** [comment]
But then the question is if we do it for record_once why not for other configuration options? That's why I opened the discussion on this feature.
