### ISSUE TITLE
path_transformer doesn't default properly

### ISSUE THREAD

**Issue by agriffis** [kevin1024/vcrpy#199]
In the code, we have

```python
class VCR(object):
    def __init__(self, path_transformer=lambda x: x, before_record_request=None,
```

and then later

```python
    def get_merged_config(self, **kwargs):
        path_transformer = kwargs.get(
            'path_transformer',
            self.path_transformer or self.ensure_suffix('.yaml')
        )
```

and then later

```python
        if 'path_transformer' in other_kwargs:
            transformer = other_kwargs['path_transformer']
            cassette_kwargs['path'] = transformer(cassette_kwargs['path'])
```

So there are two problems with this code:
  1. The default `ensure_suffix` doesn't fire because the parameter default is already the identity function which is truthy. The only way this fires is if the user specifies `path_transformer=None` which is surely not the intent.
  2. If the context manager is called with `path_transformer=None` then it will blow up.

**Comment by IvanMalison** [comment]
yeah i think you can just remove the path_transformer default and check for None or dfeault to identity it build merged config
