### ISSUE TITLE
Support aiohttp

### ISSUE THREAD

**Issue by omerbenamram** [kevin1024/vcrpy#209]
Hi,

I love vcrpy!
now that tornado support is included, any chance of supporting aiohttp anytime soon?

Cheers

**Comment by IvanMalison** [comment]
No plans to add it currently but it looks straightforward enough to do

**Comment by drgarcia1986** [comment]
:+1:  to aiohttp suport

**Comment by kevin1024** [comment]
just added, thanks @lamenezes
