### ISSUE TITLE
way to request/record only headers

### ISSUE THREAD

**Issue by yarikoptic** [kevin1024/vcrpy#211]
I am blindly (since use_cassette's docstring doesn't describe **kwargs) using ```vcr.use_cassette``` to decorate a unittest for a connection via urllib2.Request were I am interested only in the .info() to e.g. see if 'Content-Disposition' is provided.  If ran without vcr decoration, test barely consume any bandwidth since doesn't request actual load, while vcr seems to proxy/store the entirety of the response (which might be arbitrarily large).  Is the an option for the use_casssette to avoid fetching anything besides the headers?

PS not sure if ever expressed gratitude for the vcr.py -- THANK YOU!  It is a great help!

**Comment by IvanMalison** [comment]
you could use a fitlter function to delete the request/response body, i suppose.

**Comment by agriffis** [comment]
```python
my_vcr = vcr.VCR(before_record_response=lambda r: return dict(r, body={'string': b''}))
```

or something close to that. You could also use a more complex function to decide whether or not to kill the body string.

**Comment by yarikoptic** [comment]
Thanks!   FWIW -- verified that works for me. CheerS!
