### ISSUE TITLE
The @use_cassette() decorator make methods always return None

### ISSUE THREAD

**Issue by raff** [kevin1024/vcrpy#219]
For regular tests, this works fine:

@vcr.use_cassette
def test_something(self):
   # run test
   pass

But when trying to use the decorator like this:

@vcr.use_cassette
def test_with_return(self):
   # do something
   return 42

calling the decorated method always return None, while it should be returning the method result.

**Comment by IvanMalison** [comment]
This has already been fixed in https://github.com/kevin1024/vcrpy/pull/217, but it hasn't yet made it in to a release.

I'll make a new one now so you can get the update.

**Comment by dopplershift** [comment]
Any word on this release? I've got test failures induced by this and I'm trying to figure out what to do about it...

**Comment by IvanMalison** [comment]
Sorry that took so long. New release (1.7.4) with a fix is out.

**Comment by dopplershift** [comment]
No worries, thanks for maintaining such an awesome package.
