### ISSUE TITLE
Dependencies problems with Python2.7 and virtualenv

### ISSUE THREAD

**Issue by aliaksandrb** [kevin1024/vcrpy#221]
Hi!
I have faced strange dependency issue while using this library with a `tox` for testing on various Python versions.
After an investigation here are simplified steps for reproducing:

```bash
$ python --version # > Python 2.7.9
$ which python # > /usr/bin/python
$ virtualenv -p /usr/bin/python test # I have a few Python's installed
#   but need to create virtualenv for 2.7
# Running virtualenv with interpreter /usr/bin/python
# New python executable in test/bin/python
# Installing setuptools, pip, wheel...done
$ source test/bin/activate
(test)$ python --version # > Python 2.7.9
echo -e 'import vcr' > test.py
(test)$ python test.py
#Traceback (most recent call last):
# File "test.py", line 4, in <module>
#    import vcr
# ImportError: No module named vcr

# So everything is fine until now
(test)$ pip --version # > pip 7.1.2 from /tmp/test/local/lib/python2.7/site-packages (python 2.7)
(test)$ pip install vcrpy
# Collecting vcrpy
# Collecting six>=1.5 (from vcrpy)
#   Using cached six-1.10.0-py2.py3-none-any.whl
# Collecting wrapt (from vcrpy)
# Collecting PyYAML (from vcrpy)
# Installing collected packages: six, wrapt, PyYAML, vcrpy
# Successfully installed PyYAML-3.11 six-1.10.0 vcrpy-1.7.3 wrapt-1.10.5

# Now I have expected the working import as package manages its dependencies, but: 
(test)$ python test.py
# Traceback (most recent call last):
# File "test.py", line 4, in <module>
#     import vcr
#   File "/tmp/test/local/lib/python2.7/site-packages/vcr/__init__.py", line 2, in <module>
#    from .config import VCR
#   File "/tmp/test/local/lib/python2.7/site-packages/vcr/config.py", line 8, in <module>
#   from .compat import collections
#  File "/tmp/test/local/lib/python2.7/site-packages/vcr/compat.py", line 4, in <module>
#    import mock
# ImportError: No module named mock

# Woops!
```
To fix it I needed to manually install the `mock` and `contextlib2` packages, only after it import is working fine.
Seems that it is somehow related to extra dependency management done in the `setup.py` file: https://github.com/kevin1024/vcrpy/blob/master/setup.py#L30-L49, because those libs are mentioned there but for some reason wasn't installed automatically.

Is I am doing something wrong or this issue makes sense?

Would glad to fix by myself it but I am pretty new in Python world so not sure if its package/virtualenv/system related issue.

P.S. Anyway thanks a lot for such great package!

**Comment by IvanMalison** [comment]
Try running the tests with tox, which will handle the installation of all of the dependencies and the creation of the virtual machine for yu

**Comment by aliaksandrb** [comment]
@IvanMalison actually until I haven't mentioned both those dependencies in my `setup.py` and `requirements.txt` for `tox` it had failed for me.

But I have rechecked simplified example above on empty Vagrant box for **system** python, seems that dependencies are resolved correctly there..
:confused:

**Comment by IvanMalison** [comment]
Okay, I'm going to close this issue in that case
