### ISSUE TITLE
Serialization errors with JSON adapter and Python3.4

### ISSUE THREAD

**Issue by aliaksandrb** [kevin1024/vcrpy#222]
Hi!

Assume we have `vcr` configured with `json` adapter:

``` python
import vcr
vcr = vcr.VCR(serializer='json')
```

and a simple method posting some data:

``` python

def login(username, password):
    credentials = {
        'username': username,
        'password': password,
    }

    response_obj = requests.post('https://example.com/login', json=credentials)
    return response_obj
```

Then the wrapped test method fails while trying to dump the request-response into json file:

``` python
    def test_login(self):
        with vcr.use_cassette('fixtures/vcr_cassettes/invalid_login.json'):
            with self.assertRaises(client.Unauthorized):
                self.client.log_in(username='***', password='***')
```

Error outputs is reduced:

```
  File "~/.tox/py34/lib/python3.4/site-packages/vcr/serializers/jsonserializer.py", line 13, in serialize
    return json.dumps(cassette_dict, indent=4)
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 194, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'{"username": "***", "password": "***"}' is not JSON serializable
```

As I understand the problem occurs because `vcr` doesn't try to encode `request` body a counterweight to `response`.
And because in Python2.7 `body` is simple `str` type `json.dump` works correctly with it but fails on `byte` type of Python3.4.

Maybe we could try to encode request body into `utf-8` similarly to `response`, but fallback to existent behavior in case of exception? (For real binary data posting)

If it makes sense I would like to provide an PR for this.

Thanks!

**Comment by agriffis** [comment]
Thanks for the bug report! We'd definitely appreciate a PR for this, especially with tests for the JSON serializer.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
