### ISSUE TITLE
1.7.3 fails sporadically while decorating a unittest which uses boto for S3

### ISSUE THREAD

**Issue by yarikoptic** [kevin1024/vcrpy#225]
It happens more often than it doesn't happen but I haven't spotted a pattern: I hoped that I could vcr a test for my new ugly duckling (entire notebook is at http://nbviewer.ipython.org/url/www.onerussian.com/tmp/demo_vcr_boto_failure.ipynb -- just plug in your credentials)
where @vcr.use_cassete() fails with
```
CannotOverwriteExistingCassetteException: No match for the request (<Request (HEAD) https://openfmri.s3.amazonaws.com/>) was found. Can't overwrite existing cassette ('test_version_url') in your current record mode ('once').
```
First time I saw it I guessed that something in request has changed, but then when I reran (and cassette file was still there) -- it succeeded which made me puzzled.
FWIW boto 2.38.0

**Comment by agriffis** [comment]
@yarikoptic Did you figure out anything more about this?

**Comment by kevin1024** [comment]
@yarikoptic looks like your link to the failure isn't working:
<img width="779" alt="screen shot 2015-12-05 at 2 15 24 pm" src="https://cloud.githubusercontent.com/assets/21099/11610989/ad3b4806-9b5a-11e5-8fa2-97b0d95965ed.png">


You want to make 100% sure that the request you are sending matches the previous request recorded in the cassette - there might be some kind of timestamp header in there that is changing, for example.  Take a look at the request you are sending and the request that is in the cassette.

Closing for now but please reopen if you have more info!
