### ISSUE TITLE
VCR.py doesn't work well with subclasses of HTTPSConnection

### ISSUE THREAD

**Issue by chekunkov** [kevin1024/vcrpy#227]
Project I'm working on uses [chargebee python client](https://github.com/chargebee/chargebee-python). I decided to give VCR.py a try and instantly got this exception:

``` pytb
  File "/project/path/code.py", line 23, in validate_chargebee_id
    chargebee.Customer.retrieve(value)
  File "/venv/path/lib/python3.4/site-packages/chargebee/models/customer.py", line 29, in retrieve
    return request.send('get', request.uri_path("customers",id), None, env, headers)
  File "/venv/path/lib/python3.4/site-packages/chargebee/request.py", line 14, in send
    response = http.request(method, url, env, ser_params, headers)
  File "/venv/path/lib/python3.4/site-packages/chargebee/http.py", line 34, in request
    connection = compat.VerifiedHTTPSConnection(meta.netloc)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1203, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
TypeError: super(type, obj): obj must be an instance or subtype of type
```

By searching issues I've found the same exception in https://github.com/kevin1024/vcrpy/issues/183, but not sure if it's because of the same reason, hope someone more familiar with VCR.py code can tell how to fix that.

`VerifiedHTTPSConnection` is defined [here](https://github.com/chargebee/chargebee-python/blob/master/chargebee/compat.py#L47)

MRO of classes at the moment of failure:

``` python
ipdb> HTTPSConnection.__mro__
(<class 'vcr.patch.VCRHTTPSConnectioncassettes/test_webhook_events/test_add_charge'>, <class 'vcr.stubs.VCRHTTPSConnection'>, <class 'vcr.stubs.VCRConnection'>, <class 'object'>)

ipdb> self.__class__.__mro__
(<class 'chargebee.compat.VerifiedHTTPSConnection'>, <class 'http.client.HTTPSConnection'>, <class 'http.client.HTTPConnection'>, <class 'object'>)
```

Python 3.4.3
vcrpy==1.7.4
chargebee==1.5.4

**Comment by agriffis** [comment]
Thanks for the bug report. The maintainers are pretty swamped at the moment but we'd be very interested in a PR to fix this! Otherwise we'll get to it eventually, but it might be a while.

**Comment by felipead** [comment]
I'm having exactly the same issue while trying to use VCR.py along with PyGithub.

**Comment by memorysaver** [comment]
The same issue here. I want to integrate with chargebee API as well.

**Comment by memorysaver** [comment]
I notice chargebee use urllib which is not supported by vcr.py rathar than urllib2 and urllib3. I didn't look into the cause, but I think it is highly related to this issue.

Moreover, someone raised this issue at chargebee's repo. Maybe help chargebee migrate to `request` would be a better idea.
https://github.com/chargebee/chargebee-python/issues/15

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by fialovy** [comment]
I'm having a similar issue when using VCRpy to test some [ofxclient](https://pypi.org/project/ofxclient/) calls.

Dropping a breakpoint in `__init__` of `HTTPSConnection`, I see: 

```
  /home/njulian/tests/test_banking.py(166)test__getSvbCheckingAccounts()
-> self.svbClient.authenticateWithSvb()
  /home/njulian/tests/banking.py(89)authenticateWithSvb()
-> self.svb.authenticate(svbMd.username, svbMd.pin)
  /home/njulian/tests/ve/lib/python3.7/site-packages/ofxclient/institution.py(118)authenticate()
-> res = client.post(query)
  /home/njulian/tests/ve/lib/python3.7/site-packages/ofxclient/client.py(104)post()
-> h = HTTPSConnection(host, timeout=60)
> /usr/lib/python3.7/http/client.py(1367)__init__()
-> def __init__(self, host, port=None, key_file=None, cert_file=None,
(Pdb) self
<http.client.HTTPSConnection object at 0x7fde15fb7320>
(Pdb) HTTPSConnection
<class 'vcr.patch.VCRHTTPSConnectionbankingTestData.BANKING_CASSETTE_DIR/test_SvbClient_getSvbCheckingAccounts.yaml'>
(Pdb) super(HTTPSConnection, self)
*** TypeError: super(type, obj): obj must be an instance or subtype of type
(Pdb)
```

I am using:

- vcrpy==4.0.2
- ofxclient==2.0.3
- python 3.7

So I think the issue persists, if the same thing is going on here.

**Comment by niinpatel** [comment]
I just wanted to add I'm facing the same error as @fialovy on `PyGithub`

**Comment by TomasTomecek** [comment]
Interesting. I just tried VCRpy with PyGithub in one of our test cases and it recorded the response correctly and was also able to replay it.

**Comment by niinpatel** [comment]
I was using the older version of vcrpy, it seems it is working on the recent version.

**Comment by tysonholub** [comment]
This is still an issue in vcrpy 4.1.0 using latest chargebee client 2.7.5
```
self = <chargebee.compat.VerifiedHTTPSConnection object at 0x7fefdbb9b1d0>, host = 'foo-test.chargebee.com', port = None, key_file = None, cert_file = None
timeout = <object object at 0x7fefe2b4b330>, source_address = None

    def __init__(self, host, port=None, key_file=None, cert_file=None,
                 timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
                 source_address=None, *, context=None,
                 check_hostname=None, blocksize=8192):
>       super(HTTPSConnection, self).__init__(host, port, timeout,
                                              source_address,
                                              blocksize=blocksize)
E       TypeError: super(type, obj): obj must be an instance or subtype of type

../../.pyenv/versions/3.7.8/lib/python3.7/http/client.py:1389: TypeError
```
