### ISSUE TITLE
Add decode_compressed_response VCR option

### ISSUE THREAD

**Issue by tobiowo** [kevin1024/vcrpy#230]
The Ruby version of VCR supports a [decode_compressed_response](https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/cassettes/decode-compressed-response) option that decompresses response bodies encoded with gzip or deflate before recording and makes cassettes human-readable/editable. This could be implemented in vcrpy as a before_record_response function using zlib.

**Comment by IvanMalison** [comment]
seems like a good idea pr?

**Comment by kevin1024** [comment]
:+1: sounds useful to me. Would merge a pull request for this.

**Comment by agriffis** [comment]
I have this in vcrpy-facebook if you'd like to pull from that code. https://github.com/agriffis/vcrpy-facebook/blob/master/vcr_facebook/response.py#L50
