### ISSUE TITLE
tornado support crashes when used with older versions

### ISSUE THREAD

**Issue by simon-weber** [kevin1024/vcrpy#235]
[This line](https://github.com/kevin1024/vcrpy/blob/327797c4ff2dac52bc35cc7cca38439ea2453fea/vcr/stubs/tornado_stubs.py#L26) will raise an exception on tornado versions < 4 since the body_producer argument doesn't exist.

I'd also recommend a major version increment. Lots of our tests broke when upgrading because we assumed tornado wouldn't be intercepted :grin:

**Comment by simon-weber** [comment]
xref https://github.com/kevin1024/vcrpy/pull/164 and https://github.com/kevin1024/vcrpy/pull/165, which introduced the tornado support.

**Comment by kevin1024** [comment]
Oops, good point.  The fix for #208 might also be backwards-incompatible so we might do a major version bump anyway.

**Comment by simon-weber** [comment]
:+1: thanks!
