### ISSUE TITLE
vcrpy with py.test and xdist

### ISSUE THREAD

**Issue by stevezau** [kevin1024/vcrpy#248]
Hi,

We are py.test plugin xdist to improve testing runtime by running tests in parallel

We are getting random fails with cvrpy only when using more then 1 test runner such as 

https://travis-ci.org/Flexget/Flexget/jobs/115481397

I've read that vcrpy is not threadsafe but then i read there were some changes that made it threadsafe? Can someone please confirm ?

thanks!

**Comment by stevezau** [comment]
ignore this, found it might be an issue with a non-threadsafe test

**Comment by kevin1024** [comment]
Haha OK, that I can do :)
