### ISSUE TITLE
remove_post_data_parameters throws None has no split

### ISSUE THREAD

**Issue by delijati** [kevin1024/vcrpy#250]
I use requests oauth lib to auth to a service. I would like to remove the credentials added in the form. Its about the third or so request. This is possible if a simple `if request.body` is set before the for loop `for k, sep, v in (p.partition(b'=') for p in request.body.split(b'&')):`

``` python
def remove_post_data_parameters(request, post_data_parameters_to_remove):
    if request.method == 'POST' and not isinstance(request.body, BytesIO):
        if request.headers.get('Content-Type') == 'application/json':
            json_data = json.loads(request.body.decode('utf-8'))
            for k in list(json_data.keys()):
                if k in post_data_parameters_to_remove:
                    del json_data[k]
            request.body = json.dumps(json_data).encode('utf-8')
        else:
            post_data = collections.OrderedDict()
            if isinstance(request.body, text_type):
                request.body = request.body.encode('utf-8')

            if request.body:
                for k, sep, v in (p.partition(b'=') for p in request.body.split(b'&')):
                    if k in post_data:
                        post_data[k].append(v)
                    elif len(k) > 0 and k.decode('utf-8') not in post_data_parameters_to_remove:
                        post_data[k] = [v]
                request.body = b'&'.join(
                    b'='.join([k, v])
                    for k, vals in post_data.items() for v in vals)
    return request
```

**Comment by kevin1024** [comment]
Any reason you can't just use the builtin post parameter filtering? https://vcrpy.readthedocs.io/en/latest/advanced.html#filter-information-from-http-post-data

**Comment by delijati** [comment]
I'm using it. [1] But as i mentioned above its the third request in a library which contains the credentials. The request before that a some GET, GET ...

[1]
```python
@my_vcr.use_cassette(filter_post_data_parameters=["j_password", "j_username"])
    def test_get_object_by_id(self):
        ....
```

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
