### ISSUE TITLE
ETA for next pypi release?

### ISSUE THREAD

**Issue by nickdirienzo** [kevin1024/vcrpy#256]
Really cool to see #234 and a whole bunch of Python3 changes merged into master. When do you think we'll see a release on pypi? Thanks for working on this package!

**Comment by kevin1024** [comment]
Thanks for the nudge.  Maybe this weekend!

**Comment by IvanMalison** [comment]
Just released v1.8.0

**Comment by nickdirienzo** [comment]
Awesome. Thanks for the super-quick turnaround on the version bump! :)
