### ISSUE TITLE
Flaky test: `test_original_decoded_response_is_not_modified`

### ISSUE THREAD

**Issue by nickdirienzo** [kevin1024/vcrpy#261]
There have been a few failures of this test since its introduction (see #247 for some comments around this).

It's difficult to reproduce locally, but this does happen in Travis. It may have to do with differences in responses from httpbin.org/gzip, but without more verbose logging in Travis it's hard to say for sure. 

We can introduce an assertion error message that logs the decompressed content, but that'll be truncated by the current test runner (unless we run it with `-v`). If we're doing that, we might as well just decompress the content and assert on the decompressed content.

I can send out a PR for comparing the decompressed data if that seems reasonable.

**Comment by kevin1024** [comment]
Yup, just comparing the decompressed response seems to fix it.  Thanks!

**Comment by nickdirienzo** [comment]
Thanks for fixing that @kevin1024. Sorry I didn't get around to it sooner.

**Comment by kevin1024** [comment]
No worries, thanks for your contributions :)
