### ISSUE TITLE
Broken recording if use proxy server

### ISSUE THREAD

**Issue by objque** [kevin1024/vcrpy#263]
Hi,

I have local proxy server (Charles) and this code:

```python
import requests
import vcr

with vcr.use_cassette('fixtures/vcr_cassettes/synopsis.yaml'):
    response = requests.get('http://httpbin.org/get?q=w')
```

If run this code with proxy server, this VCR save broken yaml file. (in field URL)
But if i disable proxy server and remove broken yaml - VCR save valid yaml.

[yaml and stacktrace](https://gist.github.com/objque/495b0aec28c62769aa1ffd09c54e1f1a)

**Comment by kevin1024** [comment]
Yeah, there is a known issue with proxies: #214 
Happy to take a PR for a fix!  Closing this issue as duplicate.
