### ISSUE TITLE
before_record_response callback is called for each response in the cassette, not just the one that is matched

### ISSUE THREAD

**Issue by danielbrowne** [kevin1024/vcrpy#268]
`with vcr.use_cassette(
                    CASSETTE, before_record_response=self._fix_change_response, record_mode='none', serializer='json'):
                response = requests.post(
                    url='https://mock_change_server_test_connection:8443/axl/', headers=self.headers.dict)`

_fix_change_response gets called once for each record in the cassette. Should it not only be called for the record that is successfully matched?

**Comment by pakal** [comment]
From what I see, all requests/responses are loaded once at cassette startup, with their preprocessors applied immediately.
