### ISSUE TITLE
build failure under python2 with 1.10.0

### ISSUE THREAD

**Issue by nirik** [kevin1024/vcrpy#270]
byte-compiling /builddir/build/BUILDROOT/python-vcrpy-1.10.0-1.fc26.noarch/usr/lib/python2.7/site-packages/vcr/stubs/aiohttp_stubs.py to aiohttp_stubs.pyc
  File "/usr/lib/python2.7/site-packages/vcr/stubs/aiohttp_stubs.py", line 16
    def json(self, *, encoding='utf-8', loads=json.loads):  # NOQA: E999
                    ^
SyntaxError: invalid syntax

I thought aiohttp was python3 only? perhaps it should be excluded for python2 builds? Or python2 support dropped?

**Comment by kevin1024** [comment]
Aiohttp tests should not run on python2 but we definitely still support Python2.  Are you seeing this failure from your own test suite or from running VCR's test suite?

**Comment by nirik** [comment]
The full build log is at: 
https://kojipkgs.fedoraproject.org//work/tasks/8539/15408539/build.log

Fedora builds the python2 and python3 versions in the same source package... the error shows up when doing 'python2 setup.py install'

**Comment by kevin1024** [comment]
Paging @lamenezes - it looks like your asynciohttp patch broke the fedora package build.  Can you check that out?

**Comment by lamenezes** [comment]
I'm checking it.

It seems that `python setup install` works, but `python setup.py install_lib` doesn't. From the logs fedora's python setup also calls `install_lib`

I'm working on some way to exclude aiohttp codes from python 2.7 builds

**Comment by lamenezes** [comment]
@kevin1024 is there any way I can help to close/solve this issue?

**Comment by kevin1024** [comment]
Thanks for the reminder!  Merged the PR.  @nirik is master building ok for you?

**Comment by nirik** [comment]
With both the above PR's I think we are good. :) 

Are you planning a release soon? Or should I just apply these downstream in Fedora packages?

**Comment by kevin1024** [comment]
Will try to do a release this weekend :)

**Comment by kevin1024** [comment]
OK, released!
