### ISSUE TITLE
Add "recorded_with: VCR VERSION" to response

### ISSUE THREAD

**Issue by jseabold** [kevin1024/vcrpy#273]
It looks like GitHub relies on this line being present to mark a file as a cassette.

https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L336

**Comment by kevin1024** [comment]
I think you meant to open this on the Ruby VCR project, not the Python one :)

**Comment by jseabold** [comment]
Hi. No I meant this project. The Ruby VCR project includes this information. I was trying to figure out why github suppresses cassette diffs for our ruby projects but not our Python ones. AFAICT, that project is how github does file type recognition, so it doesn't recognizes cassettes generated by vcrpy as cassettes without that last bit of information stuck in the cassette objects.

**Comment by jseabold** [comment]
> This library is used on GitHub.com to detect blob languages, ignore binary or vendored files, suppress generated files in diffs, and generate language breakdown graphs.

https://github.com/github/linguist#linguist

**Comment by IvanMalison** [comment]
I'm going to cautiously reopen this issue. I know that vcrpy was never intended to inter-operate or share a format with ruby's vcr, but I think that it might be valuable to take some type of action on this. It may be that we should make a PR to linguist instead.

**Comment by jseabold** [comment]
I filed an issue on the linguist issue tracker. I still think you may need to add some identifying information to the cassettes, but you'd know better than I.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
