### ISSUE TITLE
Problem with boto3

### ISSUE THREAD

**Issue by afrosimon** [kevin1024/vcrpy#283]
This is most likely related to #247 - I've cornered where the issue is happening, but I'm unsure as to how I'd fix this problem. When using vcr.py with a pretty normal boto3 use-case (reading from s3) I stumbled upon this exception : 

  File "[...]/lib/python3.4/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 234, in connect
    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,
AttributeError: 'AWSHTTPSConnection' object has no attribute 'key_file'

It turns out that a certain check is failing : line 700 in botocore/vendored/requests/packages/urllib3/connectionpool.py

if isinstance(conn, VerifiedHTTPSConnection):

This line failing implies the "set_cert()" method is not called, which causes the aforementioned exception. Using pdb I can see that VerifiedHTTPSConnection is patched with vcr.py and that this is most likely why the isinstance() check fails.

Anyone can reproduce this issue? Here are the versions I'm using : 

vcrpy==1.10.1
boto3==1.4.0
botocore==1.4.53

**Comment by kevin1024** [comment]
Ugh, that isinstance check is a pain.  Thanks for the analysis, you're probably right.  Wonder if there is a scary metaprogrogramming method to fake out isinstance.  That or submit a patch to boto3

**Comment by smarlowucf** [comment]
> AttributeError: 'AWSHTTPSConnection' object has no attribute 'key_file'

I was getting a similar error when launching an instance with EC2 and also retrieving the instance state.

```state = instance.state['Name']```

Resolved both by importing boto3 or using  importskip on boto3 in the test module. Similar to the boto3 integration test https://github.com/kevin1024/vcrpy/blob/master/tests/integration/test_boto3.py.

```
import pytest
boto3 = pytest.importorskip("boto3")
```

**Comment by arthurHamon2** [comment]
This issue should have been fixed by https://github.com/kevin1024/vcrpy/pull/411
