### ISSUE TITLE
Requests pass trough on ci

### ISSUE THREAD

**Issue by nysthee** [kevin1024/vcrpy#287]
Hey

When running our test suite locally the cassettes are correctly loaded but on my CI I get the notice that the request from the cassette and the actual request don't match. 

There is no resemblance with #214, I didn't found any HTTP proxy related environment variables.

Python version: 3.5.2
Vrcrpy version: 1.10.4

The CI we are using uses docker to run the builds, I tried with a few different docker images but they all give the same result. 

Anything I can do to debug this?

**Comment by mandshaw** [comment]
Do you have debug on and can you see how the request and cassette differ?

I had this problem myself before where my venv locally was using an older version of requests and when I deployed to my CI it failed cause it was using a newer version of requests and the headers differed (The requests version is in the header)

I solved this by (naively) switching header checks off

**Comment by nysthee** [comment]
```vcr.cassette: DEBUG: Entering context for cassette at vcr_cassettes/imbibe_crawler.yaml.
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): imbibemagazine.com
vcr.stubs: DEBUG: Got <Request (GET) http://imbibemagazine.com/category/recipes/cocktails-spirits-recipes/>
vcr.stubs: INFO: <Request (GET) http://imbibemagazine.com/category/recipes/cocktails-spirits-recipes/> not in cassette, sending to real server
requests.packages.urllib3.connectionpool: DEBUG: http://imbibemagazine.com:80 "GET /category/recipes/cocktails-spirits-recipes/ HTTP/1.1" 200 None
vcr.cassette: DEBUG: Exiting context for cassette at vcr_cassettes/imbibe_crawler.yaml.
```

This is the response I get when logging turned on. Is this the expected output of the logger. Because according to the docs I should be able to see which matcher fails.

**Comment by mandshaw** [comment]
Ah it looks like either your cassette never got up to the CI (do you have
it included in a manifest or have you ignored it in your
gitignore/equivalent) or your record mode is not set to once.

That line 'not in cassette, sending to real server' usually happens when
you don't have a cassette or your record mode is not strict.

when the cassette exists you would see the match breaks like the document
expects but it looks like your cassette is not in your CI workspace. Can
you double check that?

**Comment by nysthee** [comment]
It was a path issue. Thank you so much for pointing me in the right direction! 👍  👍  👍

**Comment by mandshaw** [comment]
No worries, I love vcrpy. Glad to help out :)
