### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ubaldo** [kevin1024/vcrpy#290]
Hi, the fix in this merged pr https://github.com/kevin1024/vcrpy/pull/289 solves an issue we have with app engine's latest sdk. However, it's not included in the latest release, so I can't get it from pip.

Do you plan to make a release soon that includes this issue?

**Comment by kevin1024** [comment]
Thanks for the ping.  Just pushed a new release.

**Comment by lamenezes** [comment]
@kevin1024 don't forget to push the tags to github :)

**Comment by ubaldo** [comment]
That's right, no new tag, currently latest is 1.10.3

**Comment by kevin1024** [comment]
annd tagged!  Thanks :cake:
