### ISSUE TITLE
before_record_response does not change real response

### ISSUE THREAD

**Issue by Lukas0907** [kevin1024/vcrpy#291]
Hi,

when the cassette has not been recorded yet, the real response is returned that doesn't have the filter from `before_record_response` applied.

This means that the response is different depending on if it comes from the cassette or if it's the real one produced during recording.

Cheers,

Lukas

**Comment by kevin1024** [comment]
Yeah, the intention of before_record_response is to give a hook to alter the data that gets saved (e.g. to filter out passwords or something), not to change the actual response.  What's your use case?

**Comment by Lukas0907** [comment]
Thanks for your fast response! :)

I have a JSON response that contains sensitive data. I want to replace some sensitive fields with placeholders and during the first run (when the response doesn't yet come from the cassette) I also want to have the placeholders in the response. This way I can just delete the cassettes, rerun the tests and hopefully they still pass.

I could also achieve the same by writing my tests differently so that they don't rely on the replaced values. But I think it's at least surprising that the values change depending on from where the response is coming.

**Comment by kjagiello** [comment]
In my case, I'm trying to remove `Set-Cookie` from the serialised request, but it removes it from the actual response too, so it seems that it already works the way @Lukas0907 was hoping for. In my case this is however a bit troublesome as I do want the cookie in the actual response, but not in the cassettes.

**Comment by Tr4pSt3R** [comment]
@Lukas0907 should this still be marked as an issue given @kevin1024 has kindly provided us with some explanation??

**Comment by Lukas0907** [comment]
I've changed my tests so I don't need this any more. From my side, the issue can be closed.

**Comment by Tr4pSt3R** [comment]
It looks like from @kevin1024 's side this is a non-issue (_judging from his earlier explanation_)

**Comment by Lukas0907** [comment]
OK, then I'll close it.

**Comment by Tr4pSt3R** [comment]
Thank you very much @Lukas0907 👍🏾
