### ISSUE TITLE
before_record is ignored when before_record_response/request is used

### ISSUE THREAD

**Issue by AartGoossens** [kevin1024/vcrpy#297]
When a VCR instance is configured with `before_record` and `before_record_response` and/or `before_record_request`, `before_record` is ignored.
I used this as a way to prevent recording or using cassettes completely but this did not work.

### Example
```python
USE_CASSETTES = False
vcr.VCR(
    before_record=lambda request: request if USE_CASSETTES else None,
    before_record_request=lambda request: request,
    before_record_response=lambda response: response)
```
In this scenario cassettes are still used or recorded.

### Solution
I think this is intended behavior but I think the documentation should make it clear. Possibly [here](https://github.com/kevin1024/vcrpy/blame/master/docs/advanced.rst#L263).

**Comment by IvanMalison** [comment]
> before_record_response and/or before_record_request, before_record is ignored.

It's not and/or.

before_record is simply an alias for request.

The relevant line is

```
self.before_record_request = before_record_request or before_record
```

**Comment by AartGoossens** [comment]
Thanks for clearing things up @IvanMalison.
To prevent future confusion, is it an idea to replace `before_record` with `before_record_request` in the docs?

**Comment by IvanMalison** [comment]
Sure, although before_record still works. The only thing that is worth noting is that before_record_request supercedes before_record. That is, before_record will be ignored when before_record_request is present.
