### ISSUE TITLE
How to use vcr in sphinx doctests?

### ISSUE THREAD

**Issue by nhanb** [kevin1024/vcrpy#310]
I'm trying to migrate from **requests_cache** to **vcrpy**. I haven't figured out a clean way to setup vcr inside my [doctests within sphinx](http://fundoshi.nerdyweekly.com/en/latest/usage.html). Previously with **requests_cache** I could add a `testsetup` block like this at the top of the rst file:

```
.. testsetup:: *

    import requests_cache
    requests_cache.install_cache('../test_cache', allowable_methods=('GET', 'POST'))
```

But **vcrpy** does everything inside its context manager so I can't do that. Technically I can wrap every doctest snippet inside a `with vcr.use_cassette()` block but that would be horribly verbose and counter-intuitive for readers.

Am I missing something here? Has anyone figured this out?

**Comment by graingert** [comment]
If you're using pytest you can create a pytest fixture and use that.

**Comment by nhanb** [comment]
I'd rather not migrate to a different testing framework because I'm happy with the current setup and would rather keep things minimal (also I looked and haven't found an obvious way to setup pytest + doctest + sphinx that leverages fixtures to fix my issue).

Turns out I can manually start and close a context manager with `__enter__()` and `__exit__()`, so things worked out with something like this in sphinx conf file:

```python
doctest_global_setup = '''
import vcr
context = vcr.use_cassette('./doctest_cassette.yml')
context.__enter__()
'''

doctest_global_cleanup = '''
context.__exit__()
'''
```
