### ISSUE TITLE
Possibly incompatible with latest Requests release

### ISSUE THREAD

**Issue by kennethreitz** [kevin1024/vcrpy#311]
Hello,

Requests moved away from internally packaged dependencies this weekend, and as such, may have broken compatibility with this library.

Related: https://github.com/Flexget/Flexget/issues/1846#issuecomment-304471517

**Comment by kevin1024** [comment]
Thanks for the heads up!

**Comment by kennethreitz** [comment]
Sorry in advance!

**Comment by kevin1024** [comment]
@IvanMalison Something odd here, seems like urllib3 is no longer being patched properly.  I'm still poking around but a bit confused.

**Comment by kevin1024** [comment]
I'm starting to suspect this https://github.com/kennethreitz/requests/blob/master/requests/packages.py

**Comment by kennethreitz** [comment]
Well, yes. :)

**Comment by kevin1024** [comment]
The reason I'm confused is because we have always patched both requests.packages.urllib3 and urllib3 directly since vcr works with urllib3 out of the box as well, so this change should not have affected vcr.

It appears that one sys.modules line is causing the issue.  Maybe we are avoiding double-patching somehow?  I'll keep digging.

**Comment by kennethreitz** [comment]
i wonder if import order would matter — maybe requests needs to be imported after vcr

**Comment by kevin1024** [comment]
I think it has something to do with the fact that when one assigns to sys.modules (`__setitem__`), it causes the code to be reloaded, but existing references still point to the old code, so VCR is patching the old reference instead of the new.

**Comment by kennethreitz** [comment]
that's why i thought import order might matter

**Comment by kennethreitz** [comment]
you could always update sys.modules too, if needed.

**Comment by kevin1024** [comment]
I think I have a crazy workaround, only downside is my head is exploding 😜

**Comment by IvanMalison** [comment]
> I'm starting to suspect this https://github.com/kennethreitz/requests/blob/master/requests/packages.py

I'm not 100% convinced that this is to blame.

> I think it has something to do with the fact that when one assigns to sys.modules (__setitem__), it causes the code to be reloaded, but existing references still point to the old code, so VCR is patching the old reference instead of the new.

The thing is that either

a) this happened BEFORE vcrpy even attempted the requests import
or
b) vcrpy is causing the requests import

in either case we should be getting a fresh version of the module.
