### ISSUE TITLE
Issue found when trying to use vcrpy with requests and concurrent.futures

### ISSUE THREAD

**Issue by froomzy** [kevin1024/vcrpy#315]
Whilst writing a test for some new work I was doing, I encountered an issue where vcr was somehow passing a
now deprecated parameter to urllib3, or causing requests to do so. I have reproduced a minimal example below
that causes the same issue, and is doing things in much the same way that I was. I have also included a
version of the script that doesn't explode, where there is no vcr involved.

For details sake, here is the python version that the scripts were running under.
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

And here is the pip freeze (I only did pip install vcrpy requests):
```
certifi==2017.4.17
chardet==3.0.3
idna==2.5
multidict==2.1.6
PyYAML==3.12
requests==2.17.3
six==1.10.0
urllib3==1.21.1
vcrpy==1.11.1
wrapt==1.10.10
yarl==0.10.2
```

### Version One: Breaks with the bad stack trace (below)

```python
import concurrent.futures
import vcr
import requests

testing_vcr = vcr.VCR(
    cassette_library_dir='cassettes',
    record_mode='once'
)

URLS = [
    'http://www.google.com',
    'http://www.otago.ac.nz'
]

futures = []


def load_url(url, timeout):
    response = requests.get(url, timeout=timeout)
    return response.text


with testing_vcr.use_cassette('urls.yaml'):
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        futures = [executor.submit(load_url, url, 60) for url in URLS]
    done, failed = concurrent.futures.wait(futures)
    for url in done:
        print(url.result())
```

### Version Two: Does not break

```python
import concurrent.futures
import requests

URLS = [
    'http://www.google.com',
    'http://www.otago.ac.nz'
]

futures = []


def load_url(url, timeout):
    response = requests.get(url, timeout=timeout)
    return response.text


with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    futures = [executor.submit(load_url, url, 60) for url in URLS]
done, failed = concurrent.futures.wait(futures)
for url in done:
    print(url.result())
```

The stacktrace produced:
```
Traceback (most recent call last):
  File "vcr-futures-issue.py", line 61, in <module>
    print(url.result())
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "vcr-futures-issue.py", line 50, in load_url
    response = requests.get(url, timeout=timeout)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/vcr/patch.py", line 200, in patched_get_conn
    connection = get_conn(pool, timeout)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/urllib3/connectionpool.py", line 250, in _get_conn
    return conn or self._new_conn()
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/vcr/patch.py", line 221, in patched_new_conn
    new_connection = new_conn(pool)
  File "/home/dylanjenkinson/projects/python/venvs/vcrbug/lib/python3.5/site-packages/urllib3/connectionpool.py", line 211, in _new_conn
    strict=self.strict, **self.conn_kw)
TypeError: __init__() got an unexpected keyword argument 'strict'
```

Hopefully this is enough info, and if there is anything else that I can provide, please let me know.

Cheers,
Dylan

**Comment by lmazuel** [comment]
I have a similar issue, see this job on Travis for instance:
https://travis-ci.org/Azure/azure-sdk-for-python/jobs/262885406

This is a random issue on Travis, sometimes it works, sometimes it does not :/. Never fail on the first test, always somewhere later.

I tracked this down to the `ConnectionCls` attribute of `urllib3.connectionpool.HTTPSConnectionPool`, that is supposed to be mocked to `VCRHTTPSConnection`. At some point (for an unknown reason yet) it is replaced by `httplib.HTTPSConnection`, that indeed does not contain strict:
https://docs.python.org/3/library/http.client.html?highlight=http%20client#http.client.HTTPSConnection

(`httplib` being `from six.moves import http_client as httplib`)

So my current guess is that the patchs are "resetted" for an incorrect reason, but still don't know why
https://github.com/kevin1024/vcrpy/blob/v1.11.1/vcr/patch.py#L362

**Comment by lmazuel** [comment]
This might helps as well, on Py 3.3, `strict` is still a parameter of `httplib.HTTPSConnection` so the stacktrace is a little different but it fails just a little later and gives another insight:
https://travis-ci.org/Azure/azure-sdk-for-python/jobs/262885407

**Comment by graingert** [comment]
> new work
> Python 3.5.2
> concurrent.futures

@froomzy use aiohttp.

**Comment by lmazuel** [comment]
@graingert do we agree that your answer is an advice (good advice by the way :)), but this has nothing to do with the actual issue? :-)

**Comment by lmazuel** [comment]
@froomzy note that I got the problem without using concurrent at all, so I think concurrent is just making it more obvious. If you think I should just open a new issue I can, but the root cause seemed to me to be the same.

**Comment by graingert** [comment]
@lmazuel if you can repeat it without threads that would be great.

I don't want to support legacy IO on modern platforms.

**Comment by lmazuel** [comment]
@graingert that's my problem, I don't have threads, but this just happens on Travis for some reason :(. I gave what I have so far: `ConnectionCls` attribute of `urllib3.connectionpool.HTTPSConnectionPool` turns itself into `httplib.HTTPSConnection`, after some tests... 
I create `VCR` object in all my class `setUp` (and I have a lot of `TestCase`), meaning this class might be claimed by the garbage collector anytime (or never). That's my current guess, that Travis containers have less memory than me and the garbage collector is more lazy on my machine, but that something's breaking when `VCR` is disposed. But unsure, it's complicated to reproduce outside of Travis...

**Comment by graingert** [comment]
@lmazuel can you repeat it with a simple test case?

**Comment by lmazuel** [comment]
@graingert will do my best :)

**Comment by Kartstig** [comment]
I am able to repo _with_ threads. Not sure if that's helpful, but I'm using `TheadPoolExecutor.map`:
```python
def _fetch_all_direct_deps(action, idents):
    with ThreadPoolExecutor(max_workers=12) as executor:
        deps = executor.map(lambda ident: _fetch_direct_deps(action, ident), idents)
        return [ result for result in deps ]
```

**Comment by lmazuel** [comment]
@graingert I opened https://github.com/kevin1024/vcrpy/pull/326, which I think fixes the `strict` issue. But this is not enough to fix the while problem, now it just fails later, but trying to do an actual request. So it seems for some reasons the mock are lost, after a call to `reset_patchers`

**Comment by jaraco** [comment]
I've hit this issue too in a thread-based web server (cherrypy). Is it fixed? Is a release planned?

**Comment by hartwork** [comment]
> TypeError: __init__() got an unexpected keyword argument 'strict'

Related: https://github.com/kevin1024/vcrpy/pull/340#issuecomment-357770497

**Comment by jaraco** [comment]
The issue I've encountered does seem to be helped by using the master of the repo. Is a release planned?

**Comment by kevin1024** [comment]
You're right, we probably should do a new release.
