### ISSUE TITLE
`requests` and HTTPS connection gives an error

### ISSUE THREAD

**Issue by zaufi** [kevin1024/vcrpy#318]
Hi,

I'm trying to record a session with REST API of [JFrog Artifactory](https://jfrog.io). I use [verified HTTPS session](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) and everything is fine until I add a `vcr.use_cassette` decorator to my test. With decorator the test failed with multiple exceptions first of which is (reported by `py.test`):

    >           raise RemoteDisconnected("Remote end closed connection without"
                                        " response")
    E           http.client.RemoteDisconnected: Remote end closed connection without response

    /usr/lib64/python3.5/http/client.py:266: RemoteDisconnected

    During handling of the above exception, another exception occurred:

Also there is "strange" message appeared in stdout:

    /usr/lib64/python3.5/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning)

... but I've used a verified connection in fact.

Any idea how to fix/avoid this? (I can provide any needed details)

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
