### ISSUE TITLE
If test leaks an unfinished thread with a requests.Session, next test fails for wrong cassette.

### ISSUE THREAD

**Issue by lmazuel** [kevin1024/vcrpy#327]
I think that's the root cause of #315, and I got to fix #326 to help me to figure this out.

If you think about `mock.patch`, questioning about multi-thread safety is the bad question ([see this interesting SO question](https://stackoverflow.com/a/26877522/4074838)). However, what happen if a thread keeps a `requests.Session` object with a patched connectionpool, but the main thread exits the `@vcr.use_cassette` test? The `__exit__` of patch does not fail, the `__exit__` of `CassetteContextDecorator` does not fail either, but the patch stays in place for a short period of time. If the next test starts quickly enough, this silently fails to patch with the new cassette, and leads to the wrong file being read:

> vcr.errors.CannotOverwriteExistingCassetteException: No match for the request (<Request (POST) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Media/CheckNameAvailability?api-version=2015-10-01>) was found. Can't overwrite existing cassette ('/home/travis/build/Azure/azure-sdk-for-python/azure-mgmt-eventgrid/tests/recordings/test_azure_mgmt_eventgrid.test_eventgrid_user_topics.yaml') in your current record mode ('once').

You have to trust me on this, but `CheckNameAvailability` is being recorded in [test_mgmt_media.test_media.yaml](https://github.com/Azure/azure-sdk-for-python/blob/d4083fc3751d072eec3194531a966728bd03a3ec/azure-mgmt-media/tests/recordings/test_mgmt_media.test_media.yaml)

The full Travis job with VCRPy in Debug mode is here: https://travis-ci.org/Azure/azure-sdk-for-python/jobs/266929923

See that the request of the next test (test_mgmt_media) is applied to the matchers of the old test (test_azure_mgmt_eventgrid). This should be impossible, since I left the VCRPy context manager:

> DEBUG:vcr.matchers:Requests <Request (POST) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Media/CheckNameAvailability?api-version=2015-10-01> and <Request (PUT) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test_azure_mgmt_eventgrid_test_eventgrid_user_topics3e2215a6/providers/Microsoft.EventGrid/topics/kalspython1/providers/Microsoft.EventGrid/eventSubscriptions/kalspythonEventSubscription2?api-version=2017-06-15-preview> differ according to the following matchers: [(False, <function method at 0x7fdd4ffe3048>), (False, <function path at 0x7fdd4fdc7620>), (False, <bound method ReplayableTest._custom_request_query_matcher of <class 'test_azure_mgmt_eventgrid.MgmtEventGridTest'>>)]

Note that I `Thread.join`-ed all my threads in my test before leaving, and now everything is fixed on my side. I open this as a friend, just in case someone else hit that :). This should be at least a recommendation when I search "thread" in the doc that all thread should be "joined/stopped" before leaving the VCRpy context manager, or you can't ensure any behavior. My two cents, again in friendly mode.

For full info, I don't use the `@vcr.use_cassette` decorator, instead I have a base class that do a setup that way (but I think it's legit):
```python
        cm = self.vcr.use_cassette(self.recording_file)
        self.cassette = cm.__enter__()
        self.addCleanup(cm.__exit__)
```

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
