### ISSUE TITLE
return (yield from fn(cassette)) works only with python3

### ISSUE THREAD

**Issue by zobelhelas** [kevin1024/vcrpy#330]
In *vcrpy/vcr/_handle_coroutine.py* you have:
```
import asyncio


@asyncio.coroutine
def handle_coroutine(vcr, fn):
    with vcr as cassette:
        return (yield from fn(cassette))  # noqa: E999
```
This results in 
```
  File "/usr/lib/python2.7/dist-packages/vcr/_handle_coroutine.py", line 7
    return (yield from fn(cassette))  # noqa: E999
                     ^
SyntaxError: invalid syntax

```

Your setup.py claims the package should work with 2.7, which it seems it does not.

**Comment by kevin1024** [comment]
Whoops.  Will merge a PR that fixes this.

**Comment by graingert** [comment]
@zobelhelas this exception should be caught

**Comment by graingert** [comment]
Here: https://github.com/kevin1024/vcrpy/blob/master/vcr/cassette.py#L18

**Comment by zobelhelas** [comment]
That is interesting, as it fails to install on Debian unstable:

```
zobel@gjallar ~/projects/debian/packages % sudo dpkg -i python-vcr_1.11.1-1_all.deb
[sudo] password for zobel: 
(Reading database ... 306505 files and directories currently installed.)
Preparing to unpack python-vcr_1.11.1-1_all.deb ...
Unpacking python-vcr (1.11.1-1) over (1.11.1-1) ...
Setting up python-vcr (1.11.1-1) ...
  File "/usr/lib/python2.7/dist-packages/vcr/_handle_coroutine.py", line 7
    return (yield from fn(cassette))  # noqa: E999
                     ^
SyntaxError: invalid syntax

dpkg: error processing package python-vcr (--install):
 subprocess installed post-installation script returned error exit status 101
Errors were encountered while processing:
 python-vcr
```

Debian's install script runs:
```
# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
        pycompile -p python-vcr 
fi

# End automatically added section

```

**Comment by graingert** [comment]
@zobelhelas that's a Debian packaging issue. They need to patch out that file for Python 2 builds. What happens if you use the official package from the repos or pip

**Comment by zobelhelas** [comment]
@graingert i am currently preparing the upload of 1.11.1 to Debian. Do you want me to finally disable python2 support for this module?

**Comment by graingert** [comment]
@zobelhelas you should be able to simply delete `vcr/_handle_coroutine.py` on the python 2 build

**Comment by eriol** [comment]
@graingert thanks for the hint, I will remove `vcr/_handle_coroutine.py` on the Python 2 build, I'm finalizing the Debian package of vcr.py.
@zobelhelas vcr.py is maintained under the umbrella of Debian Python Module Team[¹], I'm the actual maintainer, but feel free to work on it. However, I'm updating it right know.

Another problem with Debian vcr.py packaging is a test related to TLS1 that is failing because on Debian TLS 1.0 and TLS 1.1 were disabled.
I built the package on Debomatic, you can see results here:
http://debomatic-amd64.debian.net/distribution#unstable/vcr.py/1.11.1-1/buildlog

[¹] https://tracker.debian.org/pkg/vcr.py

**Comment by zobelhelas** [comment]
@eriol Thanks alot. I am aware of the fact you managing the package within the Debian Python Team. My intention was to file a wishlist new-upstream bug, with the patch attached. I currently need the package updated, as i work on several Azure related packages, where vcrpy is within the dependency-tree. Issue can be closed then from my PoV.

**Comment by eriol** [comment]
@zobelhelas sorry for the delay, I had problems with some failing tests due to bump on minimum TLS supported version. I uploaded vcr.py 1.11.1-1 to unstable: https://tracker.debian.org/news/874683.
Many thanks to all for the support!

**Comment by graingert** [comment]
@eriol @zobelhelas cool, I'm assuming I can close this issues then
