### ISSUE TITLE
vcrpy fails to record requests made in setup and teardown 

### ISSUE THREAD

**Issue by FrankSalad** [kevin1024/vcrpy#331]
If I declare a test like this:

```
class Example(TestCase):
    def setUp(self):
        # Network requests here
    @vcr.use_cassette()
    def test_case(self):
        # Other things, other requests
```

The requests made in setUp are not recorded. 

This issue is not remedied by using the VCRTest [unit test integration](https://vcrpy.readthedocs.io/en/latest/usage.html#unittest-integration)

**Comment by j-funk** [comment]
did you try decorating the `setUp`?

```
    @vcr.use_cassette()
    def setUp(self):
        # Network requests here
```

**Comment by FrankSalad** [comment]
@j-funk that would work if subsequent tests didn't rely on setUp creating a fresh new state with every call. If we decorate `setUp`, the cassette created will works with `test_case1`, but then if it gets used while recording `test_case2` it won't work because `test_case2` expects that `setUp` would have created a fresh user. 

```
class Example(TestCase):
    @vcr.use_cassette()
    def setUp(self):
        # Network requests to create a user here
    @vcr.use_cassette()
    def test_case1(self):
        # Other things, other requests expecting a fresh user 1
    @vcr.use_cassette()
    def test_case2(self):
        # Other things, other requests expecting a fresh user 2
```

We're specifically using vcr to mock out Stripe, in case you were wondering. Thanks for the great library 💯

**Comment by j-funk** [comment]
You have to forgive me for saying, but this seems like an issue with the way your tests/system under test are designed more than an issue with VCR.  If your tests are hermetic ie. no side effects or shared fixtures (like a DB instance), then you'll have a better time testing.  

A brute force workaround would be to create a helper function like `make_network_request()` and call that from each test.  Then the decorator in each test will work the way you intend and you avoid most of the code duplication.

**Comment by FrankSalad** [comment]
@j-funk yup, that's the strategy we're using. It just involves a bit more refactoring that we'd initially anticipated. I just wanted to raise an issue to highlight something that tripped us up in our initial consideration of VCR as a drop-in solution for our existing test suite. 

It might be worth adding an example of this usage (annotating the setUp) and this potential gotcha in the docs.

**Comment by harrislapiroff** [comment]
I also encountered this issue when trying to write tests around the Stripe API. It's certainly an architecturally tricky one...

**Comment by coolo** [comment]
I tried annotating setUp, but in my testing all tests use the setUp cassette then. The test doesn't switch the cassette in the middle of the run.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
