### ISSUE TITLE
What is the recommended way of using vcpy with boto3?

### ISSUE THREAD

**Issue by jonathan-willis** [kevin1024/vcrpy#333]
I created a bunch of tests using vcrpy with boto3 without really looking under the hood at what was going on and just enjoying the magic.

Now I see that the requests are based on the settings in my environment (ex: region, credentials). If any of those change (which they have) the tests break.

I also just noticed the uri has changed for some boto calls which are breaking tests.
Example:
vcrpy is trying to match:
<Request (POST) https://cloudfront.amazonaws.com/2017-03-25/origin-access-identity/cloudfront>
while the cassette contains:
https://cloudfront.amazonaws.com/2016-11-25/origin-access-identity/cloudfront

What is the recommended way to use this with boto3 so that it ignores these changing elements?

Update: modifying the cassettes to use the new cloudfront uri fixed the tests affected by the uri issue, but is there a better way than find/replace?

Thanks

**Comment by kevin1024** [comment]
You can filter that information from the request: http://vcrpy.readthedocs.io/en/latest/advanced.html#filter-sensitive-data-from-the-request

Then it will not be stored in the cassette so it shouldn't be used for matching.

**Comment by jonathan-willis** [comment]
What about matching the cloudfront requests? Do I have to create a custom matcher so that in the future when they update their url again it doesn't break my tests? I imagine I'm not the only one using vcrpy with boto3. This along with any other issues that I'm probably not covering must be resolved already by someone.

**Comment by kevin1024** [comment]
Yup you could do that with a custom matcher.  Not aware of a more "universal" technique.

**Comment by jonathan-willis** [comment]
Ok thanks.
