### ISSUE TITLE
Tests fail on master beacause of Python 2.6 support

### ISSUE THREAD

**Issue by samuelfekete** [kevin1024/vcrpy#338]
Tests are currently failing on master because a number of libraries have stopped supporting Python 2.
What I found so far, the following don't support Python 2.6:
[wheel>=0.30.0](https://github.com/pypa/wheel/blob/7ca7b3552e55030b5d78cd90d53f1d99c9139f16/CHANGES.txt#L15) 
[ruamel.yaml>=0.12.0](https://bitbucket.org/ruamel/yaml/commits/6eca2e8f28dc2ed64f065972327be5a0e381549d?at=0.12.0) 

(There were other failing tests that I fixed in https://github.com/kevin1024/vcrpy/pull/319/commits/36b51622301b68b6e46243f83f3c9ab87809c162)

**Comment by hartwork** [comment]
My vote for dropping support for Python 2.4, 2.5, 2.6. It's 2017.

**Comment by hugovk** [comment]
👍 

Here's the pip installs for vcrpy-unittest from PyPI for the last month (via `pypinfo --percent --pip vcrpy-unittest pyversion`) showing nothing for EOL Python 2.6.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   47.5% |            699 |
| 3.6            |   43.7% |            643 |
| 3.5            |    4.8% |             70 |
| 3.4            |    4.0% |             59 |

Python 3.3 is also EOL and little used.

Dropping 2.6 and 3.3 would help reduce the burden of maintaining them, and help reduce the time it takes for the gigantic test matrix to complete.

**Comment by hugovk** [comment]
Feedback welcome on PR #340.
