### ISSUE TITLE
Does not support 'content_type' keyword for mocking version 2.3.10+ of aiohttp's Response object's json() method

### ISSUE THREAD

**Issue by avinash240** [kevin1024/vcrpy#347]
Does not support 'content_type' keyword for mocking version 2.3.10+ of aiohttp's Response object's json() method.

**Comment by k-funk** [comment]
Same issue here: https://docs.aiohttp.org/en/stable/client_advanced.html#disabling-content-type-validation-for-json-responses
Vcr blows up with `TypeError: json() got an unexpected keyword argument 'content_type'`

**Comment by lamenezes** [comment]
Fixed by PR #368. The patch will be available on the next vcrpy release.
