### ISSUE TITLE
Patching of urllib3

### ISSUE THREAD

**Issue by steveYeah** [kevin1024/vcrpy#351]
Hey @kevin1024, I had an odd issue when trying to use VCRpy on a slightly older project last week. After a lot of digging we found that we were using an older version of requests that had the vendored version of urllib3, but also had urllib3 as a separate dependency. VCRpy was discovering the separately installed urllib3, and mocked that version and ignored the requests vendored package.

After looking into it a bit more, I agree with the action that VCRpy was taking and upgraded requests to a version that didn't vendor urllib3 (well, it still pretends to, but it actually uses the installed urllib3) and all was fine.

Would it be worth me adding this possible gotcha to the documentation so that other people don't end up repeating the same steps we took, or do you think it's an edge case that isn't worth mentioning?

Thanks!

**Comment by kevin1024** [comment]
Thanks for tracking that down!  I think that’s a bug, it should be patching both, but the way requests hacked itself to remove the vendored dependency by directly manipulating sys.modules is probably messing with VCR’s monkey patching.

**Comment by steveYeah** [comment]
Just to clarify, In our case it was an actual vendored version of urllib3 that wasn't being patched, as it was an older version on Requests, but it was patching the install urllib3 package. The upgrade to the new version of Requests was OK. Let me know if you need any more info. Thanks!

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
