### ISSUE TITLE
Integration w. Twitter API

### ISSUE THREAD

**Issue by dimitrismistriotis** [kevin1024/vcrpy#358]
Hi, do not know if this is the right place to ask, thought to give it a try. Fell free to close issue if off topic.

I was trying to record interactions with Twitter through https://github.com/bear/python-twitter/ . Although the API call was run from a test with successful results, there was no cassette being recorded. API uses requests under the hood (https://github.com/bear/python-twitter/blob/master/twitter/api.py#L30).

How could I make this work? my aim is to build a test where some processing happens on Tweets kind of pinning down the results so that tests will work on the same response.

I asked in SO copy-pasting the question here:

I want to use https://github.com/bear/python-twitter/ and check API requests https://github.com/kevin1024/vcrpy or https://github.com/agriffis/vcrpy-unittest.

From lines 30:

https://github.com/bear/python-twitter/blob/master/twitter/api.py#L30

    30: import requests

and later on:

            res = requests.post(url='https://api.twitter.com/oauth2/token',
                                data={'grant_type': 'client_credentials'},
    headers=post_headers)
            # ... etc ...

Yet when doing something like:

    from vcr_unittest import VCRTestCase
    import vcr
    import twitter
    from django.conf import settings
    
    
    class TwitterRetrievalAndStorageTests(VCRTestCase):
        @vcr.use_cassette()
        def test_recorded_session(self):
            api = twitter.Api(
                consumer_key=settings.TWITTER_CONSUMER_KEY,
                consumer_secret=settings.TWITTER_CONSUMER_SECRET,
                access_token_key=settings.TWITTER_ACCESS_KEY,
                access_token_secret=settings.TWITTER_ACCESS_SECRET)
    
            statuses = api.GetUserTimeline(screen_name='nntaleb')
            for s in statuses:
                print(s)

Not a cassette file is being created. Is there a way to do this with python-twitter?

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by dimitrismistriotis** [comment]
+1 for cleaning up. For the current need I used official Twitter's official API, then pickled its output and then used pickles in a mock. From using vcrpy elsewhere I have no issues so 100% agree on your decision.
