### ISSUE TITLE
When using aiohttp - VCRpy does not save the query parameters

### ISSUE THREAD

**Issue by gciding** [kevin1024/vcrpy#364]
Hi

I'm using VCRpy to record a set of several http requests in the form:

* https://www.foo.bar/?item=123
* https://www.foo.bar/?item=456

E.g. We're adding support for code written as:

```python
url = "https://www.foo.bar/?item=456"
async with session.get(url) as response:
        content = await response.text()
```

as opposed to:

```python
base_url = "https://www.foo.bar/"
query_params = {"item": 46}
async with session.get(base_url, params=query_params) as response:
        content = await response.text()
```

However, the current VCRpy implementation strips the query parameters in the first example when saving the cassette.

My suspicion was it was the line `request_url = URL(url).with_query(params)` in the aiohttp stub.  The `with_query` call clobbers any existing params and instead replaces them with only params specified in the argument.

I've adjusted the code and tested that VCRpy now works correctly for these urls. Demonstration in Pull Request #361

**Comment by lamenezes** [comment]
@gciding thanks for submitting the issue and the PR. I believe this is going to be solved on the next vcrpy release.
