### ISSUE TITLE
Python 3.7 support 

### ISSUE THREAD

**Issue by lsmithso** [kevin1024/vcrpy#373]
Does vcrpy support Python 3.7.0? If not is such support planned?

Our vcrpy tests are failing when run with Python 3.7.0. They work fine
with Python 2.7 and earlier versions of Python 3. vcrpy is failing to
match requests to cassette files. However when stepped through with a
debugger the matching works fine. I see a lot of coroutine code in
cassette.py. Is there some kind of race with Python 3.7.0.

I ran the vcrpy tests from the latest master and got the attached
errors. Included are what look like coroutine errors.

**Comment by lamenezes** [comment]
@lsmithso thans for taking your time and opening this issue. vcrpy 2.0 has been just released with py37 support so this issue should be solved. I'm closing this for now and if the problem persists feel free to open other issue.
