### ISSUE TITLE
allow_playback_repeats functionality

### ISSUE THREAD

**Issue by aqw** [kevin1024/vcrpy#392]
VCR's ``allow_playback_repeats`` option provides the ability to basically de-duplicate multiple identical requests made in the same session.
https://relishapp.com/vcr/vcr/docs/request-matching/playback-repeats

I have been unable to turn up similar functionality in vcrpy (though I did find it was the original behavior prior to version 0.4)

I agree with the default behavior being what it is, but it would be nice to have the option to allow this matching. Does this functionality already exist (and I just missed it) or are their plans to add it?

---Alex

**Comment by syst3mw0rm** [comment]
I'd like to use this functionality as well.

**Comment by adamJLev** [comment]
Me three! This would be a nice addition to this great library, thank you

**Comment by neozenith** [comment]
This should be an easy check, but I thought it was already doing this in v2.1.0. I'll check today at work.

I agree it'd be handy in keeping cassettes small in deduplicating identically matched requests.

**Comment by matthewarmand** [comment]
Any update on this? Haven't been able to find any documentation on how to accomplish this in `vcrpy` yet

**Comment by neozenith** [comment]
I was reading through the changelog and there is in fact no equivalent of `allow_playback_repeats`.

It treats every request, even duplicates, as unique when recording and replaying. As the same request may respond slightly differently each time, for example a timestamp.

Closing this for now but PRs are welcome to introduce this behavior if it is desired.
