### ISSUE TITLE
VCRPy 2.0.0 doesn't work on 3.4 anymore

### ISSUE THREAD

**Issue by lmazuel** [kevin1024/vcrpy#393]
My Travis job is now failing on 3.4:
```python
    import vcr
../../../virtualenv/python3.4.6/lib/python3.4/site-packages/vcr/__init__.py:2: in <module>
    from .config import VCR
../../../virtualenv/python3.4.6/lib/python3.4/site-packages/vcr/config.py:10: in <module>
    from .cassette import Cassette
../../../virtualenv/python3.4.6/lib/python3.4/site-packages/vcr/cassette.py:19: in <module>
    from ._handle_coroutine import handle_coroutine
E     File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/vcr/_handle_coroutine.py", line 1
E       async def handle_coroutine(vcr, fn):  # noqa: E999
E               ^
E   SyntaxError: invalid syntax
```

I did nothing else than installing the 2.0.0 and starting the same job as usual (requests based recording).

Does VCRPy 2.0.0 still supports 3.4? The 2.7 job works as expected, so my guess is there is condition a little loose on loading async code.

**Comment by lamenezes** [comment]
aiohttp stub doesn't work for python 3.4 on vcrpy 2.0 as stated on the changelog [1] and the release notes [2].

[1] https://vcrpy.readthedocs.io/en/latest/changelog.html
[2] https://github.com/kevin1024/vcrpy/releases/tag/v2.0.0

**Comment by lmazuel** [comment]
@lamenezes I don't use aiohttp at all, just requests. If you look closely, this stacktrace comes from `import vcr`, so there is nothing I can do.

If VCRPy as a whole is not compatible with 3.4 I got no trouble with that, but then mae it clear in ChangeLog: VCRPy does not support 3.4 anymore. And on PyPi as well (3.4 descriptor is still there).

**Comment by lmazuel** [comment]
Found the issue in the code:
```python
try:
    from asyncio import iscoroutinefunction
    from ._handle_coroutine import handle_coroutine
except ImportError:
    def iscoroutinefunction(*args, **kwargs):
        return False

    def handle_coroutine(*args, **kwags):
        raise NotImplementedError('Not implemented on Python 2')
```
In Python 2.7, asyncio does not exist, so you get an `ImportError`, which is caught here. On Python 3.4, asyncio does exist, so the second line is tried to e imported. this file contains async/await syntax, which is not valid in 3.4, and raise a `SyntaxError`. This one is not caught.

Possible fix would be to split this into asyncio / ImportError in one try/except, and handle_coroutine / SyntaxError in another try / except

**Comment by lamenezes** [comment]
Thanks for opening the issue and helping debug @lmazuel. I've just released vcrpy 2.0.1 and it should now work correctly with python 3.4.

**Comment by lamenezes** [comment]
@jxltom well pointed! I think we should pin `yarl` only for python3.4. can you open a PR fixing this? :slightly_smiling_face:

**Comment by jxltom** [comment]
@lamenezes Sure, PR https://github.com/kevin1024/vcrpy/pull/409 is up. :D
