### ISSUE TITLE
filter_post_data_parameters not working with aiohttp

### ISSUE THREAD

**Issue by cinemascop89** [kevin1024/vcrpy#398]
When trying to use the `filter_post_data_parameters` argument with the aiohttp client, vcrpy crashes with the folowing traceback:

```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "test.py", line 20, in main
    await do_request(client)
  File "test.py", line 12, in do_request
    async with client.post('https://httpbin.org/post', data=data) as response:
  File "/home/ego/devel/experiments/vcrpy_aiohttp/env/lib/python3.6/site-packages/aiohttp/client.py", line 855, in __aenter__
    self._resp = await self._coro
  File "/home/ego/devel/experiments/vcrpy_aiohttp/env/lib/python3.6/site-packages/vcr/stubs/aiohttp_stubs/__init__.py", line 57, in new_request
    if cassette.can_play_response_for(vcr_request):
  File "/home/ego/devel/experiments/vcrpy_aiohttp/env/lib/python3.6/site-packages/vcr/cassette.py", line 254, in can_play_response_for
    request = self._before_record_request(request)
  File "/home/ego/devel/experiments/vcrpy_aiohttp/env/lib/python3.6/site-packages/vcr/config.py", line 253, in before_record_request
    request = function(request)
  File "/home/ego/devel/experiments/vcrpy_aiohttp/env/lib/python3.6/site-packages/vcr/filters.py", line 100, in replace_post_data_parameters
    splits = [p.partition(b'=') for p in request.body.split(b'&')]
AttributeError: 'dict' object has no attribute 'split'
```

Bellow is the code used to produce this error:

```python
from pprint import pprint
import asyncio

import vcr
import aiohttp

async def do_request(client):
    data = {
        'user': 'foo',
        'password': 'bar',
    }
    async with client.post('https://httpbin.org/post', data=data) as response:
        print('status', response.status)
        pprint(await response.json())


async def main():
    with vcr.use_cassette('cassettes/test.yaml', filter_post_data_parameters=['password']):
        async with aiohttp.ClientSession() as client:
            await do_request(client)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

This was detected using vcrpy 2.0.1 and aiohttp 3.4.4

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by vEpiphyte** [comment]
@neozenith We should probably keep this open, tag it as aiohttp and ensure that vcrpy is filtering aiohttp post requests properly.

**Comment by neozenith** [comment]
Hi, I just wanted to update active PRs and issues to let you know I will no longer be an active maintainer on this project.

I recently changed jobs where I no longer use VCRpy or Python at all so I don't have the bandwidth anymore. I won't be monitoring issues or PRs either.

I will have to delegate to other maintainers or ask for some contributors to step up.

I know the Azure CLI uses VCRpy so it would be nice if they could spare some sprint time to maintain this project as it was invaluable in our CI when I was using it.

Kind regards,
Josh

**Comment by vprakashplanview** [comment]
I have a potential fix for this issue. Will be submitting a PR soon

**Comment by cinemascop89** [comment]
Yes, can confirm that #572 does fix the original issue. Is there any way I can help to get this merged?

**Comment by scop** [comment]
See also #582, https://github.com/kevin1024/vcrpy/pull/572#issuecomment-820705095
