### ISSUE TITLE
Any appetite for another persistor that splits the JSON responses into individual files?

### ISSUE THREAD

**Issue by seaders** [kevin1024/vcrpy#399]
Just started switching to VCRpy, and while really awesome, I do find myself wanting to be able to tweak and edit JSON responses which are kept in individual files, which can then be properly formatted, and easier to edit, rather than as string blocks in the YAML.  So I rolled my own,

    
    class CustomPersister:
        @classmethod
        def load_cassette(cls, cassette_fpath, serializer):
            try:
                with open(cassette_fpath) as f:
                    cassette_content = f.read()
            except IOError:
                raise ValueError('Cassette not found.')
    
            cassette = deserialize(cassette_content, serializer)
            responses = cassette[1]
            if responses:
                cassette_path = Path(cassette_fpath)
                bodies_dir: Path = cassette_path.parent / cassette_path.stem
                for i, resp in enumerate(responses):
                    path = bodies_dir / f'{i}.json'
                    jresp = json.loads(path.read_text())
                    resp['body'] = \
                        dict(string=json.dumps(jresp['resp_body']).encode())
    
            return cassette
    
        @staticmethod
        def save_cassette(cassette_fpath, cassette_dict, serializer):
            response_bodies = [json.loads(r.pop('body', {}).pop('string', ''))
                               for r in cassette_dict['responses']]
            data = serialize(cassette_dict, serializer)
            cassette_path = Path(cassette_fpath)
            if response_bodies:
                bodies_dir: Path = cassette_path.parent / cassette_path.stem
                if not bodies_dir.is_dir():
                    bodies_dir.mkdir(parents=True)
                for i, body in enumerate(response_bodies):
                    path = bodies_dir / f'{i}.json'
                    req = cassette_dict['requests'][i]
                    with open(str(path), 'w') as f:
                        json.dump(dict(
                            req_url=req.url,
                            req_body=json.loads(req.body) if req.body else {},
                            resp_body=body), f)
    
            with open(cassette_path, 'w') as f:
                f.write(data)

In a "default" way, if you'd done

    @vcr.use_cassette()
    def test_login(self):
         ....

And produced 2 calls in test_login, you'd end up with a structure of,

./test_login.yaml
./test_login/0.json
./test_login/1.json

And you're then able to go in and edit 0 and 1 .json to your hearts' desire.

If there's appetite for this, I'll do it up a little more proper (and maybe less Python 3), and PR it.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
