### ISSUE TITLE
Yaml.load is disabled in PyYAML 5.x

### ISSUE THREAD

**Issue by scarabeusiv** [kevin1024/vcrpy#424]
With the new release of PyYAML the package partly refuses to work:

YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

**Comment by jeking3** [comment]
That is a warning, not a failure.

**Comment by 1oglop1** [comment]
I think that I fixed it in #411

**Comment by jeking3** [comment]
Yes, sadly it looks like the maintainer is missing...

**Comment by arthurHamon2** [comment]
This has been fixed in https://github.com/kevin1024/vcrpy/pull/449
https://github.com/kevin1024/vcrpy/pull/449/commits/9f203d73c0e218e96c4758910c05bc9f4b102ca4
