### ISSUE TITLE
Question: When is the next release due?

### ISSUE THREAD

**Issue by mbag** [kevin1024/vcrpy#428]
Hello @kevin1024 

first of all, thanks for your work on this cool and useful library.  
I was wondering when is the next release due, as I noticed that there were few commits added since last release.   
Namely I'm interested in commit `4e990db32e` that solved `collection.abc` deprecation warning. For the moment, I fixed this by using direct link to mentioned commit in the `requirements.txt`, but it would be great to have this as part of the tagged release.

Many thanks again for developing and maintaining this library.

**Comment by kevin1024** [comment]
Thanks for the poke.  Hopefully will have more time for vcr.py soon.

**Comment by mbag** [comment]
OK, thanks. Looking forward to it. I'll close this issue.
