### ISSUE TITLE
Drop legacy python support 

### ISSUE THREAD

**Issue by 1oglop1** [kevin1024/vcrpy#434]
I'd like to open a discussion about dropping support for legacy python to make our lives easier.
I came across multiple issues during development or #411 especially during CI tests, most issues with tests were simply fixed by testing on python versions `3.5, 3.6, 3.7`.

Moreover `requests` and other packages are dropping legacy python as well (more info at https://python3statement.org)

On the top of that `requests3` are in development. 

I think project can benefit from that and we can maintain less code.

What do you think about it?

**Comment by hugovk** [comment]
Please see PR #435 as a first step to drop EOL Python 3.4.

**Comment by hugovk** [comment]
Please see PR https://github.com/kevin1024/vcrpy/pull/443 to drop legacy Python 2.7.

**Comment by neozenith** [comment]
Getting addressed in PR #499
