### ISSUE TITLE
v2.1.x release

### ISSUE THREAD

**Issue by jasongi-actu** [kevin1024/vcrpy#447]
There hasn't been a release since September 2018. The collections.abc (#416) fix hasn't been deployed yet which will mean vcr.py stops working on 3.8. 3.8 goes live on 2019-10-21, but is already in beta. I think it's a good idea to pre-empt everybody's tests failing when they upgrade by doing a release.

**Comment by neozenith** [comment]
@arthurHamon2 has put a tonne of work in the last few days as well. So that is due to be released. 

The 3.8 launch sounds like a reasonable time line to aim for getting a release out.

**Comment by arthurHamon2** [comment]
@neozenith @jasongi-actu I have already fix this compatibility issue on my fork, let me 1 or 2 days to create a PR and then I will need your reviews in order to merge it, I'll keep you in touch !

**Comment by neozenith** [comment]
As a matter of organisation would it be worth setting up a gitter channel to coordinate organisational activities separate from issues and PRs?

https://gitter.im/

**Comment by neozenith** [comment]
To capture what we want to release for v2.1.x the list as far as I'm aware is:
 - Python 3.8 support
 - Fix TravisCI and test matrix
 - [WIP] #382 `boto3` compatability (Potentially target v2.2?)
 - Improved matcher nearest match messages
     - TODO: Update readthedocs documentation for this 

@arthurHamon2 ... anything I missed? 

Normally I'd run this to get an idea of changes relative to last tagged release.
```bash
git log --oneline $(git describe --tags $(git rev-list --tags --max-count=1))...master
```

@kevin1024 @IvanMalison as the most experienced contributors on this project could I get some guidance on the release process for:
 - PyPI
 - Readthedocs

I'd like to get this documented in the Contributing guide so I have a reference for subsequent releases.

**Comment by arthurHamon2** [comment]
@neozenith I have also merge multiple pending PRs that fix various bugs. I would like to merge as much as possible for the next release. Could you help me posting messages to the pending PR in order to ask the contributors to rebase their branch with master ?

**Comment by neozenith** [comment]
Sounds good. I'll start doing that as part of daily rounds.

**Comment by kevin1024** [comment]
Make sure you update the changelog before release.  For pypi - it’s just build the sdist, build the wheel, and publish.  For RTD - good question.  I think it’s supposed to auto build?  I can add you to pypi, as a maintainer - just let me know your username over there.

**Comment by neozenith** [comment]
Ok thanks. 

I realised after I asked it’s probably a well documented thing elsewhere on PyPA. 

Here is my PyPI user. 

https://pypi.org/user/neozenith/

**Comment by kevin1024** [comment]
Ok, you’re in on pypi.  Thanks so much for your work!

**Comment by neozenith** [comment]
As discussed in https://github.com/kevin1024/vcrpy/pull/443, the next release (v2.1.x) should introduce a deprecation warning for Python2.7 support where v3.x will officially drop support.

**Comment by neozenith** [comment]
Tracking all related issues and pull requests that are between us and a release in this milestone:

https://github.com/kevin1024/vcrpy/milestone/2

**Comment by neozenith** [comment]
reopenning as #470 is still open
