### ISSUE TITLE
Update ReadTheDocs for v2.1.0

### ISSUE THREAD

**Issue by neozenith** [kevin1024/vcrpy#470]
I've gone through the upload and release process.

Not sure what is left to do to get the RTD to update. I'm going to need @kevin1024's help or permissions to modify the vcrpy project on RTD.

https://readthedocs.org/projects/vcrpy/builds/

**Comment by kevin1024** [comment]
@neozenith I believe I just added you as a maintainer on readthedocs.  Let me know if that worked!

**Comment by neozenith** [comment]
What a world we live in. Just published latest docs from my phone. Thanks a lot @kevin1024!!

**Comment by neozenith** [comment]
Also what are your thoughts on perhaps transferring ownership to a github organization?

eg, canonical VCRpy starts living under:

https://github.com/vcrpy/vcrpy

In a personal account there can only be one owner. Moving to an organization could alleviate the bus factor by allowing multiple owners to steward the project.

cc: @arthurHamon2
