### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' when processing header object

### ISSUE THREAD

**Issue by rohanrane** [kevin1024/vcrpy#474]
```
headers = {'X-Amz-Target': b'<target>', 'Content-Type': b'<content-type>', 'User-Agent': b'<user-agent>', Signature=b'<sig>', 'Content-Length': '<len>'}

    def checker(headers):
>       return value in headers.get(header, '').lower()
E       TypeError: a bytes-like object is required, not 'str'

.venv/lib/python3.6/site-packages/vcr/matchers.py:56: TypeError
```

The code on line 56 in matchers fails unexpectedly. The content type return as a bytes like object   but the code still fails. When we convert the bytes object to a string it works. Replacing the current function at https://github.com/kevin1024/vcrpy/blob/master/vcr/matchers.py#L54-L57:
```
def _header_checker(value, header='Content-Type'):
    def checker(headers):
        return value in headers.get(header, '').lower()
    return checker
```
with  
```
def _header_checker(value, header='Content-Type'):
    def checker(headers):
        return value in headers.get(header, '').decode('utf-8').lower()
    return checker
```
fixes this issue especially with boto3 requests. 

Would there be any risk with making this change?

**Comment by neozenith** [comment]
@arthurHamon2 do you have any thoughts or bandwidth on the checkers?

**Comment by rohanrane** [comment]
Hey appending to this issue I also ran into a scenario where methods from boto3 could also return a string object. We'd probably need to account for this as well through a if stmt checking the type of the header passed in and then decoding or keeping the value as is. The complete change would be as follows:

```
def _header_checker(value, header='Content-Type'):
    def checker(headers):
        if type(headers.get(header, '')) is bytes:
            return value in headers.get(header, '').decode('utf-8').lower()
        else:
            return value in headers.get(header, '').lower()
    return checker
```

**Comment by neozenith** [comment]
If you have the bandwidth, please feel free to open a PR and add these as tests.

Then between you, me and TravisCI we can iterate on getting this patched.

**Comment by neozenith** [comment]
even linking to a toy git repo that replicates the issue helps a lot

**Comment by simahawk** [comment]
Hello, I have the same issue. I don't see any PR here. Anyone here has a WIP? @rohanrane ?
Otherwise I could try it.

**Comment by simahawk** [comment]
there you go https://github.com/kevin1024/vcrpy/pull/488
