### ISSUE TITLE
How to add support for a custom in-house HTTP requests library?

### ISSUE THREAD

**Issue by ichorid** [kevin1024/vcrpy#486]
Hi!
In [Tribler torrent client](https://github.com/Tribler/tribler) Qt-based GUI uses our [custom Qt-based HTTP requests module](https://github.com/Tribler/tribler/blob/devel/TriblerGUI/tribler_request_manager.py) to connect to the core process. We [would like to automate](https://github.com/Tribler/tribler/issues/4750) GUI testing by using vcrpy` library to record its communications with the core. However, `vcrpy` obviously does not support our in-home requests module.

What would be the best strategy to capture the requests with `vcrpy` in this case (in-house custom HTTP requests module)?

Thanks

**Comment by neozenith** [comment]
Hi @ichorid 

Great question!

I'm a part time maintainer and not the original author but I hadn't seen this feature until just now but it looks like you can:

```python
VCR(custom_patches=(obj, patched_attribute, replacement_object))
```
https://vcrpy.readthedocs.io/en/latest/advanced.html#custom-patches

Which passes it onto `Cassette`. Then applies it during `CassettePatcherBuilder`.

The mocked triple is a `tuple` of the same args that `mock.patch.object` accepts.

https://docs.python.org/3/library/unittest.mock.html#patch-object

----

I hope that is helpful. I'm going to mark this as closed for now but please feel free to comment or reopen if there is more that we can help you with.

Kind regards

Josh

**Comment by baronet2** [comment]
Hello,

I'd like to set up `vcrpy` for a project that uses the `agithub.API` class to make requests (see https://github.com/mozilla/agithub/blob/9f44e8f862161dd5f5b6f65ee812e173291b5132/agithub/base.py).
However, I can't seem to figure out the appropriate way to set up the `custom_patches`. Any pointers on how this can be done?

So far, I've tried (where `api` is an instance of `agithub.API`):
```python
my_vcr = vcr.config.VCR(custom_patches=((api, 'client', VCRHTTPSConnection),))
my_vcr = vcr.config.VCR(custom_patches=((api.client, 'request', vcr.request.Request),))
my_vcr = vcr.config.VCR(custom_patches=((api.client, 'request', vcr.stubs.VCRHTTPSConnection.request),))
```

If @neozenith is still involved with this project, maybe you would have a suggestion?

I'm on `vcrpy 4.1.1`, `agithub 2.2.2`, `Python 3.9.4`. Let me know if there is anything else I can provide.

Thanks!
