### ISSUE TITLE
Create a snapshot test framework with vcrpy

### ISSUE THREAD

**Issue by arizzubair** [kevin1024/vcrpy#491]
I am working on creating test framework which compares response with previously saved response (baseline). It is similar to https://github.com/syrusakbary/snapshottest  but it will use vcrpy to store responses. 

I am planning on extending VCR class with a new record mode and adding a response matcher . 
Is there a better way to do this?

**Comment by neozenith** [comment]
That sounds like the right place to start.

I'd recommend forking and cloning this repo, then `python -m pip install -e path/to/vcrpy` to work with an editable copy.

That way if you need to make "upstream changes" to `vcrpy` then feel free to make them so you can keep going, staying productive and contribute the improvements back via PR.

Happy to work with you to get timely releases.
