### ISSUE TITLE
Can't use generated cassettes under Python 2 with Python 3 and vice-versa

### ISSUE THREAD

**Issue by dupduplarafan2** [kevin1024/vcrpy#494]
Hello, i am currently working on the **migration of my code from Python 2 to Python 3.**

My problem is that when i am using the lib to use a cassette (generated under Python 2) under Python 3 i get the Error **"Can't overwrite existing cassette"**. The same occur when i am using a cassette (generated under Python 3) under Python 2.

Right now the only solution i found is to create a cassette file which is used only when i am under Python 2 and an other cassette file that which is used only when i am under Python 3 .. this is convenient for my project..

I've already looked at the issue  [https://github.com/kevin1024/vcrpy/issues/163] that is already closed, and the related PR does not seem to fix the issue for me 

Or maybe there is a solution that i missed? 

vcrpy version : 2.1.0 (both Python 2 and Python 3)

thanks for your answer.

**Comment by neozenith** [comment]
Hello and thanks for reporting this issue. I can imagine many people are tracking through the same python 2 to 3 journey this month.

Are you able to link to a toy repo that generates a _python2 cassette_ and _python3 cassette_ and commit those cassettes to the repo along with the code that generated it?

I only have bandwidth to act as a release manager these days, so any assistance to help the next person to be able to close out a PR is thoroughly welcomed.

**Comment by matmarczak** [comment]
I tried to reproduce issue with `vcrpy 2.1.0` on Python `2.7.17` and `3.6.8` but no errors found . 

More specific info on environment conf and vcrpy usage will be great facilitation here.

**Comment by hartwork** [comment]
Python 2 is dead, closing as obsolete…
