### ISSUE TITLE
Change urlib2 to urilib.request in the usage page of docs

### ISSUE THREAD

**Issue by AthulMuralidhar** [kevin1024/vcrpy#534]
- As we all know python 2 has reached its end of life this year (2020) and there are some libraries that changed names etc.
- In the usage page of vcrpy we see that the examples still use `urlib2` that has since changed. The link is here: https://vcrpy.readthedocs.io/en/latest/usage.html
- We need to change it to `urlib.request`as per python docs: https://docs.python.org/3.5/library/urllib.request.html#module-urllib.request

**Comment by 1oglop1** [comment]
you are more than welcome to PR this change I believe someone will be able to review it ;)
