### ISSUE TITLE
Discussion: websockets recording ?

### ISSUE THREAD

**Issue by asmodehn** [kevin1024/vcrpy#539]
Hi all,

I have been using vcrpy for a while now, mainly via pytest-recording to record and test my code by replaying known traffic, for a REST API. I've been developing an aiohttp-based client and it has helped me a lot to detect server behavior changes.

I started a few months ago to get into the websocket aspect of the client I am writing, and I was wondering if it would be feasible/suitable/maintainable to have a similar record/replay feature for websockets ? 
Is there a fundamental limitation somewhere or not, and if doable, what steps would be needed ?

I opened this issue mainly to gather some feedback and get the discussion going, but feel free to let me know if there is a more appropriate place.

As far as I know, most websocket usecases still require some "request" before response traffic starts coming in, so I am guessing it *could be doable* similarly to the usual HTTP usecase, provided that the user specifies some limit to the inbound traffic she/he would want to record...

What do you think ?

**Comment by nikicat** [comment]
I think is's definitely need to be done. Actually, I've found this issue while searching for VCRpy for gRPC (grpclib that works over hyper2) because gRPC request/response stream is very similar to websocket connection.

**Comment by IvanMalison** [comment]
> I started a few months ago to get into the websocket aspect of the client I am writing, and I was wondering if it would be feasible/suitable/maintainable to have a similar record/replay feature for websockets?

> Is there a fundamental limitation somewhere or not, and if doable, what steps would be needed ?

It's far beyond the scope of what this library is intended to do. Doing this would require patching raw IO requests, and furthermore, because raw sockets have far less structure than http, there's not really a clear way to structure things in a request response format.

I really doubt that vcrpy will ever do anything that does not relate to http in some way.
