### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by Justintime50** [kevin1024/vcrpy#555]
When using `vcrpy`, the following warning continues to crop up across our projects (Python 3.6, 3.7, 3.8):

```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if not isinstance(before_record_request, collections.Iterable):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

It looks like we could fix this pretty easily by changing the import and usage of `abc` from collections?

See this PR as another example of how to correct this: https://github.com/kevin1024/vcrpy/pull/416/files

```python
from collections import abc

...
if not isinstance(before_record_response, collections.abc.Iterable):
...
```

A simple fix to the following lines should do the trick to remove this warning:
- https://github.com/kevin1024/vcrpy/blob/master/vcr/config.py#L3
- https://github.com/kevin1024/vcrpy/blob/master/vcr/config.py#L168
- https://github.com/kevin1024/vcrpy/blob/master/vcr/config.py#L214

**Comment by graingert** [comment]
`from six.moves import collections_abc`

**Comment by graingert** [comment]
but it's been available since 3.3 so might not need six there

**Comment by Justintime50** [comment]
After looking at it more, we were using `v2.*` on a couple projects which is why this warning came up. This may not be valid knowing this - upgrading to `v4.*` fixed this for us on this project. I'll report back as I go across others.

**Comment by Justintime50** [comment]
Yeah this was fixed in a recent version, using `v4.*` seems to fix this.
