### ISSUE TITLE
travis ci is dead, ci should probably be moved to github actions

### ISSUE THREAD

**Issue by IvanMalison** [kevin1024/vcrpy#601]

**Comment by Crocmagnon** [comment]
What about travis-ci.com? I haven't closely followed the announcements, have they switched to a non-free model for FOSS projects ?

**Comment by IvanMalison** [comment]
they seem to be hanging on by a thread thuogh. github actions seems like a better option to me.

**Comment by Crocmagnon** [comment]
An easy win may be then to first move to Travis-ci.com and then rework the pipelines for GitHub actions.

**Comment by IvanMalison** [comment]
@Crocmagnon I mean PRs welcome. I don't think any of our many maintainers are really very active anymore, but I'm happy to merge things.

**Comment by dogweather** [comment]
@IvanMalison I'd really like to help maintain. I'd like to cut a new package version and clean up the open PR's. I haven't contributed to this project yet, but you can check out my GitHub profile.

**Comment by IvanMalison** [comment]
Probably best to ask @kevin1024

**Comment by jairhenrique** [comment]
Done https://github.com/kevin1024/vcrpy/pull/610
