### ISSUE TITLE
VCR does not accept `pathlib.Path` as cassette path

### ISSUE THREAD

**Issue by Alexander-Serov** [kevin1024/vcrpy#622]
```
>>>from pathlib import Path
>>>@vcr.use_cassette(Path('./my_path.yml'))
>>>def test():
>>>    pass
TypeError: module, class, method, function, traceback, frame, or code object was expected, got WindowsPath
```
Using `Path` is a common way of storing platoform-independent pahts. It should be easy to adapt `vcrpy` to using them: could just convert to `str` if `Path`.

**Comment by mhearne-usgs** [comment]
I would actually be fine with this behavior if vcrpy errored out as well - as it stands now, it just inexplicably doesn't write the cassette.

**Comment by 07pepa** [comment]
since i wanted this functionality too i wrote this Pull requests https://github.com/kevin1024/vcrpy/pull/658 
that fixes this

**Comment by kevin1024** [comment]
This PR has been merged! Thanks for your contribution
