### ISSUE TITLE
Add httpx to compatible HTTP client list

### ISSUE THREAD

**Issue by tyler-8** [kevin1024/vcrpy#626]
[This list](https://github.com/kevin1024/vcrpy/blob/8c0bb73658e300065eddfafc569e656e1ef6f7bf/docs/installation.rst#compatibility) is missing `httpx` which is supported as of https://github.com/kevin1024/vcrpy/pull/523 and has had [multiple issues](https://github.com/kevin1024/vcrpy/issues?q=httpx) opened & resolved since then.

**Comment by tyler-8** [comment]
I was so focused on the RTD page that I overlooked the inclusion on the actual file.

The httpx entry IS missing here: https://vcrpy.readthedocs.io/en/latest/installation.html

but not in the docs of the repo itself: https://github.com/kevin1024/vcrpy/blob/8c0bb73658e300065eddfafc569e656e1ef6f7bf/docs/installation.rst#compatibility - so I suppose it's just RTD that needs updating.

**Comment by pawelad** [comment]
I think this should be open until the changes are visible at [vcrpy.readthedocs.io/en/latest/installation.html](https://vcrpy.readthedocs.io/en/latest/installation.html) (not sure how the docs are build and deployed).
