### ISSUE TITLE
Package with latest changes

### ISSUE THREAD

**Issue by cperezabo** [kevin1024/vcrpy#648]
Are you planning to deploy latest changes to PyPI? I'm requiring vcrpy from github at the moment but it's dirty.
Last release is from 2020 and many changes were applied since then.

**Comment by dogweather** [comment]
I just realized the same thing. I'm going to go see how to pull from a commit with Poetry...

**Comment by boechat107** [comment]
@kevin1024 made a new release a week ago: https://github.com/kevin1024/vcrpy/releases/tag/v4.2.0
