### ISSUE TITLE
Question! Using VCR mechanics to record queries to sql database. 

### ISSUE THREAD

**Issue by igor-polynets** [kevin1024/vcrpy#665]
Does anyone know if there are any libraries that would allow to record and play queries to sql database? 
I don't per-see any obstacles in implementation. The question is does it even makes sense in terms of test speed improvement?

**Comment by jairhenrique** [comment]
@igor-polynets if you use in your project an ORM, maybe this libraries can help you!

- https://github.com/model-bakers/model_bakery
- https://github.com/FactoryBoy/factory_boy

**Comment by igor-polynets** [comment]
Thanks @jairhenrique I'm aware of these. 
We do use ORM, however many tests are written using models directly, and they access test database. 
I was looking for a generic solution to reduce time of these tests running by applying something similar like vcrpy.

**Comment by kevin1024** [comment]
That would be super cool!  But it outside the scope of the `vcrpy` project itself.
