### ISSUE TITLE
Route requests to different cassette files depending on host

### ISSUE THREAD

**Issue by Jasonca2** [kevin1024/vcrpy#676]
I have various hosts that I need to hit for a unit test. I'd like to be able to route the responses from each host to its own specific cassette file. The documentation does not appear to show an example of how to do this. Is there a recommended way of doing this?

**Comment by kevin1024** [comment]
Check out the `path_transformer` and `func_path_generator` configuration vars.

They are not well documented but I believe they will do what you want.

https://vcrpy.readthedocs.io/en/latest/advanced.html?highlight=path_transformer#automatic-cassette-naming
