### ISSUE TITLE
Release 4.4.0 before going 5.0.0?

### ISSUE THREAD

**Issue by hartwork** [kevin1024/vcrpy#724]
Hi! :wave:

Since release 4.3.1 we have merged the following pull requests to `master`:

- #644
- #674
- #702
- #704
- #712
- #713
- #717
- #718
- #720
- #721
- #722
- #723

I believe it would be nice to have one last 4.x.x release 4.4.0 with these changes before going 5.x.x.

@kevin1024  would you be up for cutting a release 4.4.0 from latest `master` shortly?
(Latest commit is 8b97fd65512a52f4d90b10a80fa4eca7bc8f07b9 as of the moment.)

Thanks and best, Sebastian

CC @jairhenrique @amosjyng

---

PS: Known upcoming for soon 5.0.0 so far:

- #681
- #695

**Comment by kevin1024** [comment]
Nice! Yes I should have time to cut a release this weekend.  Excellent work!  Lots of good stuff in this release.

**Comment by hartwork** [comment]
@kevin1024 cool! :tada:

**Comment by hartwork** [comment]
@kevin1024 any news?

**Comment by kevin1024** [comment]
v4.4.0 is released!

**Comment by kevin1024** [comment]
> With both https://github.com/kevin1024/vcrpy/pull/681 and https://github.com/kevin1024/vcrpy/pull/695 merged now, if you're still in releasing mode: 5.0.0 would be ready to go in my view. What do you think?

Let's GOO!

**Comment by hartwork** [comment]
@kevin1024 cool!

**Comment by kevin1024** [comment]
It's live!  https://pypi.org/project/vcrpy/

**Comment by hartwork** [comment]
@kevin1024 very nice, thank you!
