### ISSUE TITLE
Release 5.1.0 before going 6.0.0?

### ISSUE THREAD

**Issue by hartwork** [kevin1024/vcrpy#749]
Hi! :wave:

Since release 5.0.0 I believe we have merged the following pull requests to `master`:

- #727
- #729
- #732
- #735
- #738
- #739
- #740
- #743
- #745
- #746
- #747
- #748

I believe it would be nice to have one last 5.x.x release 5.1.0 with these changes before going 6.x.x.

@kevin1024 would you be up for cutting a release 5.1.0 from latest `master` shortly?
(Latest commit is e7c00a4bf9539bbe0fd04eabbeb28d1a92651795 as of the moment.)

Thanks and best, Sebastian

CC @jairhenrique

---

PS: Known upcoming for soon 6.0.0 so far:

- #731

**Comment by kevin1024** [comment]
That is awesome! Yes I should have time soon.

**Comment by kevin1024** [comment]
released!

**Comment by hartwork** [comment]
@kevin1024 thank you! :pray:
