### ISSUE TITLE
Backport patch to fix test failures with Python 3.12: AttributeError: type object 'VCRHTTPConnection[…]' has no attribute 'debuglevel'

### ISSUE THREAD

**Issue by evschlobnik** [kevin1024/vcrpy#781]
This issue was found and supposedly fixed here https://packages.fedoraproject.org/pkgs/python-vcrpy/python3-vcrpy/fedora-39.html on 2023-07-04

We have automated testing on 3.8, 3.9, 3.10, and 3.11.
The problem only occurs when we attend testing for python 3.12.  The complete error message I'm getting is 
"AttributeError: type object 'VCRHTTPSConnectiontests/fixtures/vcr_cassettes/build_radar_test/test_add_radar_to_cache.yaml' has no attribute 'debuglevel'. Did you mean: 'set_debuglevel'?"

**Comment by hartwork** [comment]
@evschlobnik this seems to be referring to patch https://src.fedoraproject.org/rpms/python-vcrpy/blob/rawhide/f/backport-patch-to-fix-AttributeError-type-object-VCR.patch of which we have a bigger version from pull request #754 merged into `master` as commit 69621c67fb29dedd9ece4a7bdbf50380fbe4c5ee. I'm closing this as "fixed on `master`", happy to re-open as needed.
