### ISSUE TITLE
Support for urllib3 >= v2.0.0

### ISSUE THREAD

**Issue by justanotherboy** [kevin1024/vcrpy#868]
Are there plans to support urllib3 verison 2.0.0 and above?

Is there a way to help with adding support?

**Comment by pjonsson** [comment]
Urllib3 version 2 works for Python >3.9 after #830 was merged, but that is after vcrpy 6.0.1 was released.

**Comment by sathieu** [comment]
@kevin1024 Is a release planned soon 🙏 ?
